name: 'ra_data_warehouse'
version: '0.0.3'

require-dbt-version: ">=0.17.0"
config-version: 2

profile: 'ra_data_warehouse'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

on-run-start:
    - "create table if not exists {{ generate_prefixed_target_name() }}_logs.audit_dbt_results (object string, status string, row_count numeric, execution_time numeric, load_ts timestamp)"

on-run-end:
    - "insert into {{ generate_prefixed_target_name() }}_logs.audit_dbt_results (object, status, row_count, execution_time, load_ts) values {{ results_values(results) }}"

models:
  ra_data_warehouse:
# source adapter general settings
      sources:
          materialized: view
          schema: staging
# integration layer settings
      integration:
          materialized: view
          schema: staging

# warehouse layer settings
      warehouse:
          materialized: table
# util module settings
      utils:
          materialized: table
          schema: logs

# seeds (reference files, loaded into tables) module settings
seeds:
  ra_data_warehouse:
    schema: seed

vars:
  crm_warehouse_company_sources: []
  crm_warehouse_contact_sources: []
  crm_warehouse_conversations_sources: []
  marketing_warehouse_ad_campaign_sources: []
  marketing_warehouse_ad_campaign_performance_sources: []
  marketing_warehouse_ad_performance_sources: []
  marketing_warehouse_ad_group_sources: []
  marketing_warehouse_ad_sources: []
  marketing_warehouse_email_event_sources: []
  marketing_warehouse_email_list_sources: []
  marketing_warehouse_deal_sources: []
  projects_warehouse_delivery_sources: []
  projects_warehouse_timesheet_sources: []
  finance_warehouse_invoice_sources: []
  finance_warehouse_transaction_sources: []
  finance_warehouse_payment_sources: []
  product_warehouse_event_sources: []
  subscriptions_warehouse_sources: []

  stg_asana_projects_id-prefix: asana-
  stg_asana_projects_etl: stitch
  stg_asana_projects_stitch_database:
  stg_asana_projects_stitch_schema:
  stg_asana_projects_staff_email_domain: .com
  stg_asana_projects_stitch_workspaces_table: "{{ source('stitch_asana_projects', 'workspaces') }}"
  stg_asana_projects_stitch_projects_table: "{{ source('stitch_asana_projects', 'projects') }}"
  stg_asana_projects_stitch_tasks_table: "{{ source('stitch_asana_projects', 'tasks') }}"
  stg_asana_projects_stitch_users_table: "{{ source('stitch_asana_projects', 'users') }}"

  stg_looker_usage_stats_id-prefix: looker-
  stg_looker_usage_database:
  stg_looker_usage_schema:
  stg_looker_usage_stats_table:

  stg_facebook_ads_id-prefix: fbads-
  stg_facebook_ads_etl: segment
  stg_facebook_ads_stitch_database:
  stg_facebook_ads_stitch_schema: stitch_facebook_ads
  stg_facebook_ads_stitch_ad_performance_table: "{{ source('stitch_facebook_ads', 'insights') }}"
  stg_facebook_ads_stitch_ad_performance_table_snowflake: "{{ source('stitch_facebook_ads', 'ads_insights') }}"
  stg_facebook_ads_stitch_ad_groups_table: "{{ source('stitch_facebook_ads', 'ad_sets') }}"
  stg_facebook_ads_stitch_ad_groups_table_snowflake: "{{ source('stitch_facebook_ads', 'adsets') }}"
  stg_facebook_ads_stitch_ads_table: "{{ source('stitch_facebook_ads', 'ads') }}"
  stg_facebook_ads_stitch_campaigns_table: "{{ source('stitch_facebook_ads', 'campaigns') }}"
  stg_facebook_ads_segment_database:
  stg_facebook_ads_segment_schema: facebook_ads
  stg_facebook_ads_segment_ad_performance_table: "{{ source('segment_facebook_ads', 'insights') }}"
  stg_facebook_ads_segment_ad_groups_table: "{{ source('stitch_facebook_ads', 'ad_adsets') }}"
  stg_facebook_ads_segment_ads_table: "{{ source('segment_facebook_ads', 'ads') }}"
  stg_facebook_ads_segment_campaigns_table: "{{ source('segment_facebook_ads', 'campaigns') }}"

  stg_google_ads_id-prefix: gads-
  stg_google_ads_etl: stitch
  stg_google_ads_stitch_database:
  stg_google_ads_stitch_schema: stitch_google_ads
  stg_google_ads_stitch_campaign_performance_table: "{{ source('stitch_google_ads', 'CAMPAIGN_PERFORMANCE_REPORT') }}"
  stg_google_ads_stitch_campaigns_table: "{{ source('stitch_google_ads', 'campaigns') }}"
  stg_google_ads_segment_database:
  stg_google_ads_segment_schema: google_ads
  stg_google_ads_segment_campaign_performance_table: "{{ source('segment_google_ads', 'campaign_performance_reports') }}"
  stg_google_ads_segment_ad_performance_table: "{{ source('segment_google_ads', 'ad_performance_reports') }}"
  stg_google_ads_segment_ad_groups_table: "{{ source('segment_google_ads', 'ad_groups') }}"
  stg_google_ads_segment_ads_table: "{{ source('segment_google_ads', 'ads') }}"
  stg_google_ads_segment_campaigns_table: "{{ source('segment_google_ads', 'campaigns') }}"
  ads_campaigns_only: true

  stg_segment_events_id-prefix: segment-
  stg_segment_events_etl: segment
  stg_segment_events_segment_database:
  stg_segment_events_segment_schema:
  stg_segment_events_segment_tracks_table: "{{ source('segment', 'tracks') }}"
  stg_segment_events_segment_pages_table: "{{ source('segment', 'pages') }}"
  stg_segment_events_segment_users_table: "{{ source('segment', 'users') }}"
  stg_segment_events_site: rittmananalytics.com
  enable_event_type_mapping: true

  stg_baremetrics_analytics_id-prefix: baremetrics-
  stg_baremetrics_analytics_etl:
  stg_baremetrics_analytics_etl: segment
  stg_baremetrics_analytics_segment_schema: baremetrics
  stg_baremetrics_analytics_segment_plan_breakdown_table: plan_breakdown

  stg_harvest_projects_id-prefix: harvest-
  stg_harvest_projects_etl: stitch
  stg_harvest_projects_stitch_database:
  stg_harvest_projects_stitch_schema: rittman_analytics
  stg_harvest_projects_staff_email_domain: rittmananalytics.com
  stg_harvest_projects_stitch_companies_table: "{{ source('stitch_harvest_projects', 'companies') }}"
  stg_harvest_projects_stitch_contacts_table: "{{ source('stitch_harvest_projects', 'contacts') }}"
  stg_harvest_projects_stitch_invoices_table: "{{ source('stitch_harvest_projects', 'invoices') }}"
  stg_harvest_projects_stitch_invoice_line_items_table: "{{ source('stitch_harvest_projects', 'invoice_line_items') }}"
  stg_harvest_projects_stitch_projects_table: "{{ source('stitch_harvest_projects', 'projects') }}"
  stg_harvest_projects_stitch_tasks_table: "{{ source('stitch_harvest_projects', 'tasks') }}"
  stg_harvest_projects_stitch_project_tasks_table: "{{ source('stitch_harvest_projects', 'project_tasks') }}"
  stg_harvest_projects_stitch_timesheets_table: "{{ source('stitch_harvest_projects', 'timesheets') }}"
  stg_harvest_projects_stitch_users_table: "{{ source('stitch_harvest_projects', 'users') }}"
  stg_harvest_projects_stitch_user_projects_table: "{{ source('stitch_harvest_projects', 'user_projects') }}"
  stg_harvest_projects_stitch_user_project_tasks_table: "{{ source('stitch_harvest_projects', 'user_project_tasks') }}"
  stg_harvest_projects_stitch_expenses_table: "{{ source('stitch_harvest_projects', 'expenses') }}"

  stg_hubspot_crm_id-prefix: hubspot-
  stg_hubspot_crm_stitch_database:
  stg_hubspot_crm_stitch_schema: stitch_hubspot
  stg_hubspot_crm_fivetran_database:
  stg_hubspot_crm_fivetran_schema: fivetran_hubspot_euwest2
  stg_hubspot_crm_etl: stitch
  stg_hubspot_crm_stitch_companies_table: "{{ source('stitch_hubspot_crm', 'companies') }}"
  stg_hubspot_crm_stitch_contacts_table: "{{ source('stitch_hubspot_crm', 'contacts') }}"
  stg_hubspot_crm_stitch_deals_table: "{{ source('stitch_hubspot_crm', 'deals') }}"
  stg_hubspot_crm_stitch_owners_table: "{{ source('stitch_hubspot_crm', 'owners') }}"
  stg_hubspot_crm_stitch_pipeline_stages_table: "{{ source('stitch_hubspot_crm', 'pipeline_stages') }}"
  stg_hubspot_crm_stitch_deal_pipelines_table: "{{ source('stitch_hubspot_crm', 'deal_pipelines') }}"
  stg_hubspot_crm_stitch_engagements_table: "{{ source('stitch_hubspot_crm', 'engagements') }}"

  stg_hubspot_crm_fivetran_company_table: "{{ source('fivetran_hubspot_crm', 'engagements') }}"
  stg_hubspot_crm_fivetran_contact_table: "{{ source('fivetran_hubspot_crm', 'contacts') }}"
  stg_hubspot_crm_fivetran_deal_table: "{{ source('fivetran_hubspot_crm', 'deals') }}"
  stg_hubspot_crm_fivetran_owner_table: "{{ source('fivetran_hubspot_crm', 'owners') }}"
  stg_hubspot_crm_fivetran_pipeline_stage_table: "{{ source('fivetran_hubspot_crm', 'pipeline_stages') }}"
  stg_hubspot_crm_fivetran_pipeline_table: "{{ source('fivetran_hubspot_crm', 'deal_pipelines') }}"
  stg_hubspot_crm_fivetran_property_history_table: "{{ source('fivetran_hubspot_crm', 'property_history') }}"
  stg_hubspot_crm_fivetran_deal_company_table: "{{ source('fivetran_hubspot_crm', 'deal_company') }}"
  stg_hubspot_crm_fivetran_engagements_table: "{{ source('fivetran_hubspot_crm', 'engagements') }}"


  stg_hubspot_email_id-prefix: hubspot-
  stg_hubspot_email_stitch_database:
  stg_hubspot_email_stitch_schema: stitch_hubspot
  stg_hubspot_email_etl: stitch
  stg_hubspot_email_stitch_email_events_table: "{{ source('stitch_hubspot_email', 'email_events') }}"
  stg_hubspot_email_stitch_campaigns_table: "{{ source('stitch_hubspot_email', 'campaigns') }}"

  stg_intercom_messaging_id-prefix: intercom-
  stg_intercom_messaging_etl: stitch
  stg_intercom_messaging_stitch_database:
  stg_intercom_messaging_stitch_schema: stitch_intercom
  stg_intercom_messaging_stitch_contacts_table: contacts
  stg_intercom_messaging_stitch_conversations_table: conversations
  stg_intercom_messaging_tags: ["intercom", "messaging"]

  stg_jira_projects_id-prefix: jira-
  stg_jira_projects_etl: stitch
  stg_jira_projects_stitch_database:
  stg_jira_projects_stitch_schema: stitch_jira
  stg_jira_projects_staff_email_domain:
  stg_jira_projects_stitch_projects_table: "{{ source('stitch_jira_projects', 'projects') }}"
  stg_jira_projects_stitch_project_types_table: "{{ source('stitch_jira_projects', 'project_types') }}"
  stg_jira_projects_stitch_project_categories_table: "{{ source('stitch_jira_projects', 'project_categories') }}"
  stg_jira_projects_stitch_issues_table: "{{ source('stitch_jira_projects', 'issues') }}"
  stg_jira_projects_stitch_users_table: "{{ source('stitch_jira_projects', 'users') }}"
  stg_jira_projects_jira_url: rittmananalytics.atlassian.net/jira

  stg_mailchimp_email_id-prefix: mailchimp-
  stg_mailchimp_email_etl: stitch
  stg_mailchimp_email_stitch_database:
  stg_mailchimp_email_stitch_schema: stitch_mailchimp
  stg_mailchimp_email_stitch_list_members_table: "{{ source('stitch_mailchimp_email', 'list_members') }}"
  stg_mailchimp_email_stitch_reports_email_activity_table: "{{ source('stitch_mailchimp_email', 'reports_email_activity') }}"
  stg_mailchimp_email_stitch_lists_table: "{{ source('stitch_mailchimp_email', 'lists') }}"
  stg_mailchimp_email_stitch_campaigns_table: "{{ source('stitch_mailchimp_email', 'campaigns') }}"

  stg_mixpanel_events_id-prefix: mixpanel-
  stg_mixpanel_events_stitch_database:
  stg_mixpanel_events_fivetran_database:
  stg_mixpanel_events_stitch_schema: mixpanel_stitch
  stg_mixpanel_events_fivetran_schema: fivetran_mixpanel
  stg_mixpanel_events_etl: fivetran
  stg_mixpanel_events_fivetran_event_table: "{{ source('fivetran_mixpanel_events', 'event') }}"
  stg_mixpanel_events_stitch_event_table: "{{ source('stitch_mixpanel_events', 'event') }}"
  stg_mixpanel_events_site: rittmananalytics.com





  stg_xero_accounting_id-prefix: xero-
  stg_xero_accounting_etl: stitch
  stg_xero_accounting_stitch_database:
  stg_xero_accounting_stitch_schema: xero
  stg_xero_accounting_stitch_accounts_table: "{{ source('stitch_xero_accounting', 'accounts') }}"
  stg_xero_accounting_stitch_payments_table: "{{ source('stitch_xero_accounting', 'payments') }}"
  stg_xero_accounting_stitch_categories_table: "{{ source('stitch_xero_accounting', 'tracking_categories') }}"
  stg_xero_accounting_stitch_bank_transactions_table: "{{ source('stitch_xero_accounting', 'bank_transactions') }}"
  stg_xero_accounting_stitch_contacts_table: "{{ source('stitch_xero_accounting', 'contacts') }}"
  stg_xero_accounting_stitch_currencies_table: "{{ source('stitch_xero_accounting', 'currencies') }}"
  stg_xero_accounting_stitch_expense_claims_table: "{{ source('stitch_xero_accounting', 'expense_claims') }}"
  stg_xero_accounting_stitch_invoices_table: "{{ source('stitch_xero_accounting', 'invoices') }}"

  stg_enrichment_id-prefix: clearbit-
  stg_enrichment_clearbit_schema: enrichment
  stg_enrichment_clearbit_contacts_table: contacts_companies
  stg_enrichment_clearbit_companies_table: contacts_companies
  stg_enrichment_geolite_city_table: company_website.geolite_city_bq_b2b

  stg_stripe_payments_id-prefix: stripe-
  stg_stripe_payments_etl: stitch
  stg_stripe_payments_stitch_database:
  stg_stripe_payments_stitch_schema: stitch_stripe
  stg_stripe_payments_stitch_balance_transactions_table: "{{ source('stitch_stripe_payments', 'balance_transactions') }}"
  stg_stripe_payments_stitch_charges_table: "{{ source('stitch_stripe_payments', 'charges') }}"
  stg_stripe_payments_stitch_events_table: "{{ source('stitch_stripe_payments', 'events') }}"
  stg_stripe_payments_stitch_payout_transactions_table: "{{ source('stitch_stripe_payments', 'payout_transactions') }}"
  stg_stripe_payments_stitch_payouts_table: "{{ source('stitch_stripe_payments', 'payouts') }}"
  stg_stripe_payments_stitch_charges_table: "{{ source('stitch_stripe_payments', 'charges') }}"

  stg_stripe_subscriptions_id-prefix: stripe-
  stg_stripe_subscriptions_etl: segment
  stg_stripe_subscriptions_segment_database:
  stg_stripe_subscriptions_segment_schema: stripe
  stg_stripe_subscriptions_segment_customers_table: "{{ source('segment_stripe_subscriptions', 'customers') }}"
  stg_stripe_subscriptions_segment_accounts_table: "{{ source('segment_stripe_subscriptions', 'accounts') }}"
  stg_stripe_subscriptions_segment_cards_table: "{{ source('segment_stripe_subscriptions', 'cards') }}"
  stg_stripe_subscriptions_segment_coupons_table: "{{ source('segment_stripe_subscriptions', 'coupons') }}"
  stg_stripe_subscriptions_segment_discounts_table: "{{ source('segment_stripe_subscriptions', 'discounts') }}"
  stg_stripe_subscriptions_segment_invoices_table: "{{ source('segment_stripe_subscriptions', 'invoices') }}"
  stg_stripe_subscriptions_segment_plans_table: "{{ source('segment_stripe_subscriptions', 'plans') }}"
  stg_stripe_subscriptions_segment_products_table: "{{ source('segment_stripe_subscriptions', 'products') }}"
  stg_stripe_subscriptions_segment_subscriptions_table: "{{ source('segment_stripe_subscriptions', 'subscriptions') }}"
  stg_stripe_subscriptions_segment_balance_transactions_table: "{{ source('segment_stripe_subscriptions', 'balance_transactions') }}"
  stg_stripe_subscriptions_segment_charges_table: "{{ source('segment_stripe_subscriptions', 'charges') }}"
  stg_stripe_subscriptions_segment_events_table: "{{ source('segment_stripe_subscriptions', 'eventsplans') }}"
  stg_stripe_subscriptions_segment_payout_transactions_table: "{{ source('segment_stripe_subscriptions', 'payout_transactions') }}"
  stg_stripe_subscriptions_segment_payouts_table: "{{ source('segment_stripe_subscriptions', 'payouts') }}"

  web_sessionization_trailing_window: 3
  web_inactivity_cutoff: 30 * 60
  attribution_create_account_event_type: account_opened
  attribution_conversion_event_type: subscribed
  attribution_topup_event_type: account_credited
  attribution_converter_ltv: 200


  enable_companies_merge_file: true
  enable_ip_geo_enrichment: false
