set echo on
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.TRANSACTION_LINE_BOOK_MAP_LOAD`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.ITEM_PRICE_HISTORY_LOAD`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.OPPORTUNITY_LINES_LOAD`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.TRANSACTION_LINES_LOAD`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.TRANSACTION_HISTORY_LOAD`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.ITEM_LOCATION_MAP_LOAD`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.TRANSACTION_LINKS_LOAD`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.TRANSACTION_BIN_NUMBERS_LOAD`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.POSTING_ACCOUNT_ACTIVITY_LOAD`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.POSTING_ACCOUNT_ACTIVITY_PE_LOAD`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.ITEM_PRICES_LOAD`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.TRANSACTION_TAX_DETAIL_LOAD`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.TRANSACTION_BOOK_MAP_LOAD`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.ADDRESSES_LOAD`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.TRANSACTIONS_LOAD`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.TRANSACTION_ADDRESS_LOAD`'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.TRANSACTION_LINE_BOOK_MAP_LOAD` as select * from  `project-x-ray.netsuite_ddl.TRANSACTION_LINE_BOOK_MAP` where false'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.ITEM_PRICE_HISTORY_LOAD` as select * from  `project-x-ray.netsuite_ddl.ITEM_PRICE_HISTORY` where false'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.OPPORTUNITY_LINES_LOAD` as select * from  `project-x-ray.netsuite_ddl.OPPORTUNITY_LINES` where false'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.TRANSACTION_LINES_LOAD` as select * from  `project-x-ray.netsuite_ddl.TRANSACTION_LINES` where false'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.TRANSACTION_HISTORY_LOAD` as select * from  `project-x-ray.netsuite_ddl.TRANSACTION_HISTORY` where false'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.ITEM_LOCATION_MAP_LOAD` as select * from  `project-x-ray.netsuite_ddl.ITEM_LOCATION_MAP` where false'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.TRANSACTION_LINKS_LOAD` as select * from  `project-x-ray.netsuite_ddl.TRANSACTION_LINKS` where false'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.TRANSACTION_BIN_NUMBERS_LOAD` as select * from  `project-x-ray.netsuite_ddl.TRANSACTION_BIN_NUMBERS` where false'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.POSTING_ACCOUNT_ACTIVITY_LOAD` as select * from  `project-x-ray.netsuite_ddl.POSTING_ACCOUNT_ACTIVITY` where false'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.POSTING_ACCOUNT_ACTIVITY_PE_LOAD` as select * from  `project-x-ray.netsuite_ddl.POSTING_ACCOUNT_ACTIVITY_PE` where false'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.ITEM_PRICES_LOAD` as select * from  `project-x-ray.netsuite_ddl.ITEM_PRICES` where false'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.TRANSACTION_TAX_DETAIL_LOAD` as select * from  `project-x-ray.netsuite_ddl.TRANSACTION_TAX_DETAIL` where false'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.TRANSACTION_BOOK_MAP_LOAD` as select * from  `project-x-ray.netsuite_ddl.TRANSACTION_BOOK_MAP` where false'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.ADDRESSES_LOAD` as select * from  `project-x-ray.netsuite_ddl.ADDRESSES` where false'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.TRANSACTIONS_LOAD` as select * from  `project-x-ray.netsuite_ddl.TRANSACTIONS` where false'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.TRANSACTION_ADDRESS_LOAD` as select * from  `project-x-ray.netsuite_ddl.TRANSACTION_ADDRESS` where false'
nohup gcloud dataflow jobs run copy_TRANSACTION_LINE_BOOK_MAP --project=project-x-ray --region europe-west2 --gcs-location gs://dataflow-templates-europe-west2/latest/Jdbc_to_BigQuery --parameters query="select * from TRANSACTION_LINE_BOOK_MAP",connectionURL="jdbc:ns://5514691.connect.api.netsuite.com:1708;ServerDataSource=NetSuite.com;encrypted=1;Ciphersuites=Ciphersuites=TLS_RSA_WITH_AES_128_CBC_SHA;CustomProperties=(AccountID=5514691;RoleID=1057)",username="mark.rittman@rittmananalytics.com",password="Rittman123",driverClassName="com.netsuite.jdbc.openaccess.OpenAccessDriver",driverJars="gs://rixo-jdbc-europe-west2/NQjc.jar",outputTable="project-x-ray:netsuite_jdbc.TRANSACTION_LINE_BOOK_MAP_LOAD",bigQueryLoadingTemporaryDirectory="gs://rixo-jdbc-europe-west2/temp"
nohup gcloud dataflow jobs run copy_ITEM_PRICE_HISTORY --project=project-x-ray --region europe-west2 --gcs-location gs://dataflow-templates-europe-west2/latest/Jdbc_to_BigQuery --parameters query="select * from ITEM_PRICE_HISTORY",connectionURL="jdbc:ns://5514691.connect.api.netsuite.com:1708;ServerDataSource=NetSuite.com;encrypted=1;Ciphersuites=Ciphersuites=TLS_RSA_WITH_AES_128_CBC_SHA;CustomProperties=(AccountID=5514691;RoleID=1057)",username="mark.rittman@rittmananalytics.com",password="Rittman123",driverClassName="com.netsuite.jdbc.openaccess.OpenAccessDriver",driverJars="gs://rixo-jdbc-europe-west2/NQjc.jar",outputTable="project-x-ray:netsuite_jdbc.ITEM_PRICE_HISTORY_LOAD",bigQueryLoadingTemporaryDirectory="gs://rixo-jdbc-europe-west2/temp"
nohup gcloud dataflow jobs run copy_OPPORTUNITY_LINES --project=project-x-ray --region europe-west2 --gcs-location gs://dataflow-templates-europe-west2/latest/Jdbc_to_BigQuery --parameters query="select * from OPPORTUNITY_LINES",connectionURL="jdbc:ns://5514691.connect.api.netsuite.com:1708;ServerDataSource=NetSuite.com;encrypted=1;Ciphersuites=Ciphersuites=TLS_RSA_WITH_AES_128_CBC_SHA;CustomProperties=(AccountID=5514691;RoleID=1057)",username="mark.rittman@rittmananalytics.com",password="Rittman123",driverClassName="com.netsuite.jdbc.openaccess.OpenAccessDriver",driverJars="gs://rixo-jdbc-europe-west2/NQjc.jar",outputTable="project-x-ray:netsuite_jdbc.OPPORTUNITY_LINES_LOAD",bigQueryLoadingTemporaryDirectory="gs://rixo-jdbc-europe-west2/temp"
nohup gcloud dataflow jobs run copy_TRANSACTION_LINES --project=project-x-ray --region europe-west2 --gcs-location gs://dataflow-templates-europe-west2/latest/Jdbc_to_BigQuery --parameters query="select * from TRANSACTION_LINES",connectionURL="jdbc:ns://5514691.connect.api.netsuite.com:1708;ServerDataSource=NetSuite.com;encrypted=1;Ciphersuites=Ciphersuites=TLS_RSA_WITH_AES_128_CBC_SHA;CustomProperties=(AccountID=5514691;RoleID=1057)",username="mark.rittman@rittmananalytics.com",password="Rittman123",driverClassName="com.netsuite.jdbc.openaccess.OpenAccessDriver",driverJars="gs://rixo-jdbc-europe-west2/NQjc.jar",outputTable="project-x-ray:netsuite_jdbc.TRANSACTION_LINES_LOAD",bigQueryLoadingTemporaryDirectory="gs://rixo-jdbc-europe-west2/temp"
nohup gcloud dataflow jobs run copy_TRANSACTION_HISTORY --project=project-x-ray --region europe-west2 --gcs-location gs://dataflow-templates-europe-west2/latest/Jdbc_to_BigQuery --parameters query="select * from TRANSACTION_HISTORY",connectionURL="jdbc:ns://5514691.connect.api.netsuite.com:1708;ServerDataSource=NetSuite.com;encrypted=1;Ciphersuites=Ciphersuites=TLS_RSA_WITH_AES_128_CBC_SHA;CustomProperties=(AccountID=5514691;RoleID=1057)",username="mark.rittman@rittmananalytics.com",password="Rittman123",driverClassName="com.netsuite.jdbc.openaccess.OpenAccessDriver",driverJars="gs://rixo-jdbc-europe-west2/NQjc.jar",outputTable="project-x-ray:netsuite_jdbc.TRANSACTION_HISTORY_LOAD",bigQueryLoadingTemporaryDirectory="gs://rixo-jdbc-europe-west2/temp"
nohup gcloud dataflow jobs run copy_ITEM_LOCATION_MAP --project=project-x-ray --region europe-west2 --gcs-location gs://dataflow-templates-europe-west2/latest/Jdbc_to_BigQuery --parameters query="select * from ITEM_LOCATION_MAP",connectionURL="jdbc:ns://5514691.connect.api.netsuite.com:1708;ServerDataSource=NetSuite.com;encrypted=1;Ciphersuites=Ciphersuites=TLS_RSA_WITH_AES_128_CBC_SHA;CustomProperties=(AccountID=5514691;RoleID=1057)",username="mark.rittman@rittmananalytics.com",password="Rittman123",driverClassName="com.netsuite.jdbc.openaccess.OpenAccessDriver",driverJars="gs://rixo-jdbc-europe-west2/NQjc.jar",outputTable="project-x-ray:netsuite_jdbc.ITEM_LOCATION_MAP_LOAD",bigQueryLoadingTemporaryDirectory="gs://rixo-jdbc-europe-west2/temp"
nohup gcloud dataflow jobs run copy_TRANSACTION_LINKS --project=project-x-ray --region europe-west2 --gcs-location gs://dataflow-templates-europe-west2/latest/Jdbc_to_BigQuery --parameters query="select * from TRANSACTION_LINKS",connectionURL="jdbc:ns://5514691.connect.api.netsuite.com:1708;ServerDataSource=NetSuite.com;encrypted=1;Ciphersuites=Ciphersuites=TLS_RSA_WITH_AES_128_CBC_SHA;CustomProperties=(AccountID=5514691;RoleID=1057)",username="mark.rittman@rittmananalytics.com",password="Rittman123",driverClassName="com.netsuite.jdbc.openaccess.OpenAccessDriver",driverJars="gs://rixo-jdbc-europe-west2/NQjc.jar",outputTable="project-x-ray:netsuite_jdbc.TRANSACTION_LINKS_LOAD",bigQueryLoadingTemporaryDirectory="gs://rixo-jdbc-europe-west2/temp"
nohup gcloud dataflow jobs run copy_TRANSACTION_BIN_NUMBERS --project=project-x-ray --region europe-west2 --gcs-location gs://dataflow-templates-europe-west2/latest/Jdbc_to_BigQuery --parameters query="select * from TRANSACTION_BIN_NUMBERS",connectionURL="jdbc:ns://5514691.connect.api.netsuite.com:1708;ServerDataSource=NetSuite.com;encrypted=1;Ciphersuites=Ciphersuites=TLS_RSA_WITH_AES_128_CBC_SHA;CustomProperties=(AccountID=5514691;RoleID=1057)",username="mark.rittman@rittmananalytics.com",password="Rittman123",driverClassName="com.netsuite.jdbc.openaccess.OpenAccessDriver",driverJars="gs://rixo-jdbc-europe-west2/NQjc.jar",outputTable="project-x-ray:netsuite_jdbc.TRANSACTION_BIN_NUMBERS_LOAD",bigQueryLoadingTemporaryDirectory="gs://rixo-jdbc-europe-west2/temp"
nohup gcloud dataflow jobs run copy_POSTING_ACCOUNT_ACTIVITY --project=project-x-ray --region europe-west2 --gcs-location gs://dataflow-templates-europe-west2/latest/Jdbc_to_BigQuery --parameters query="select * from POSTING_ACCOUNT_ACTIVITY",connectionURL="jdbc:ns://5514691.connect.api.netsuite.com:1708;ServerDataSource=NetSuite.com;encrypted=1;Ciphersuites=Ciphersuites=TLS_RSA_WITH_AES_128_CBC_SHA;CustomProperties=(AccountID=5514691;RoleID=1057)",username="mark.rittman@rittmananalytics.com",password="Rittman123",driverClassName="com.netsuite.jdbc.openaccess.OpenAccessDriver",driverJars="gs://rixo-jdbc-europe-west2/NQjc.jar",outputTable="project-x-ray:netsuite_jdbc.POSTING_ACCOUNT_ACTIVITY_LOAD",bigQueryLoadingTemporaryDirectory="gs://rixo-jdbc-europe-west2/temp"
nohup gcloud dataflow jobs run copy_POSTING_ACCOUNT_ACTIVITY_PE --project=project-x-ray --region europe-west2 --gcs-location gs://dataflow-templates-europe-west2/latest/Jdbc_to_BigQuery --parameters query="select * from POSTING_ACCOUNT_ACTIVITY_PE",connectionURL="jdbc:ns://5514691.connect.api.netsuite.com:1708;ServerDataSource=NetSuite.com;encrypted=1;Ciphersuites=Ciphersuites=TLS_RSA_WITH_AES_128_CBC_SHA;CustomProperties=(AccountID=5514691;RoleID=1057)",username="mark.rittman@rittmananalytics.com",password="Rittman123",driverClassName="com.netsuite.jdbc.openaccess.OpenAccessDriver",driverJars="gs://rixo-jdbc-europe-west2/NQjc.jar",outputTable="project-x-ray:netsuite_jdbc.POSTING_ACCOUNT_ACTIVITY_PE_LOAD",bigQueryLoadingTemporaryDirectory="gs://rixo-jdbc-europe-west2/temp"
nohup gcloud dataflow jobs run copy_ITEM_PRICES --project=project-x-ray --region europe-west2 --gcs-location gs://dataflow-templates-europe-west2/latest/Jdbc_to_BigQuery --parameters query="select * from ITEM_PRICES",connectionURL="jdbc:ns://5514691.connect.api.netsuite.com:1708;ServerDataSource=NetSuite.com;encrypted=1;Ciphersuites=Ciphersuites=TLS_RSA_WITH_AES_128_CBC_SHA;CustomProperties=(AccountID=5514691;RoleID=1057)",username="mark.rittman@rittmananalytics.com",password="Rittman123",driverClassName="com.netsuite.jdbc.openaccess.OpenAccessDriver",driverJars="gs://rixo-jdbc-europe-west2/NQjc.jar",outputTable="project-x-ray:netsuite_jdbc.ITEM_PRICES_LOAD",bigQueryLoadingTemporaryDirectory="gs://rixo-jdbc-europe-west2/temp"
nohup gcloud dataflow jobs run copy_TRANSACTION_TAX_DETAIL --project=project-x-ray --region europe-west2 --gcs-location gs://dataflow-templates-europe-west2/latest/Jdbc_to_BigQuery --parameters query="select * from TRANSACTION_TAX_DETAIL",connectionURL="jdbc:ns://5514691.connect.api.netsuite.com:1708;ServerDataSource=NetSuite.com;encrypted=1;Ciphersuites=Ciphersuites=TLS_RSA_WITH_AES_128_CBC_SHA;CustomProperties=(AccountID=5514691;RoleID=1057)",username="mark.rittman@rittmananalytics.com",password="Rittman123",driverClassName="com.netsuite.jdbc.openaccess.OpenAccessDriver",driverJars="gs://rixo-jdbc-europe-west2/NQjc.jar",outputTable="project-x-ray:netsuite_jdbc.TRANSACTION_TAX_DETAIL_LOAD",bigQueryLoadingTemporaryDirectory="gs://rixo-jdbc-europe-west2/temp"
nohup gcloud dataflow jobs run copy_TRANSACTION_BOOK_MAP --project=project-x-ray --region europe-west2 --gcs-location gs://dataflow-templates-europe-west2/latest/Jdbc_to_BigQuery --parameters query="select * from TRANSACTION_BOOK_MAP",connectionURL="jdbc:ns://5514691.connect.api.netsuite.com:1708;ServerDataSource=NetSuite.com;encrypted=1;Ciphersuites=Ciphersuites=TLS_RSA_WITH_AES_128_CBC_SHA;CustomProperties=(AccountID=5514691;RoleID=1057)",username="mark.rittman@rittmananalytics.com",password="Rittman123",driverClassName="com.netsuite.jdbc.openaccess.OpenAccessDriver",driverJars="gs://rixo-jdbc-europe-west2/NQjc.jar",outputTable="project-x-ray:netsuite_jdbc.TRANSACTION_BOOK_MAP_LOAD",bigQueryLoadingTemporaryDirectory="gs://rixo-jdbc-europe-west2/temp"
nohup gcloud dataflow jobs run copy_ADDRESSES --project=project-x-ray --region europe-west2 --gcs-location gs://dataflow-templates-europe-west2/latest/Jdbc_to_BigQuery --parameters query="select * from ADDRESSES",connectionURL="jdbc:ns://5514691.connect.api.netsuite.com:1708;ServerDataSource=NetSuite.com;encrypted=1;Ciphersuites=Ciphersuites=TLS_RSA_WITH_AES_128_CBC_SHA;CustomProperties=(AccountID=5514691;RoleID=1057)",username="mark.rittman@rittmananalytics.com",password="Rittman123",driverClassName="com.netsuite.jdbc.openaccess.OpenAccessDriver",driverJars="gs://rixo-jdbc-europe-west2/NQjc.jar",outputTable="project-x-ray:netsuite_jdbc.ADDRESSES_LOAD",bigQueryLoadingTemporaryDirectory="gs://rixo-jdbc-europe-west2/temp"
nohup gcloud dataflow jobs run copy_TRANSACTIONS --project=project-x-ray --region europe-west2 --gcs-location gs://dataflow-templates-europe-west2/latest/Jdbc_to_BigQuery --parameters query="select * from TRANSACTIONS",connectionURL="jdbc:ns://5514691.connect.api.netsuite.com:1708;ServerDataSource=NetSuite.com;encrypted=1;Ciphersuites=Ciphersuites=TLS_RSA_WITH_AES_128_CBC_SHA;CustomProperties=(AccountID=5514691;RoleID=1057)",username="mark.rittman@rittmananalytics.com",password="Rittman123",driverClassName="com.netsuite.jdbc.openaccess.OpenAccessDriver",driverJars="gs://rixo-jdbc-europe-west2/NQjc.jar",outputTable="project-x-ray:netsuite_jdbc.TRANSACTIONS_LOAD",bigQueryLoadingTemporaryDirectory="gs://rixo-jdbc-europe-west2/temp"
nohup gcloud dataflow jobs run copy_TRANSACTION_ADDRESS --project=project-x-ray --region europe-west2 --gcs-location gs://dataflow-templates-europe-west2/latest/Jdbc_to_BigQuery --parameters query="select * from TRANSACTION_ADDRESS",connectionURL="jdbc:ns://5514691.connect.api.netsuite.com:1708;ServerDataSource=NetSuite.com;encrypted=1;Ciphersuites=Ciphersuites=TLS_RSA_WITH_AES_128_CBC_SHA;CustomProperties=(AccountID=5514691;RoleID=1057)",username="mark.rittman@rittmananalytics.com",password="Rittman123",driverClassName="com.netsuite.jdbc.openaccess.OpenAccessDriver",driverJars="gs://rixo-jdbc-europe-west2/NQjc.jar",outputTable="project-x-ray:netsuite_jdbc.TRANSACTION_ADDRESS_LOAD",bigQueryLoadingTemporaryDirectory="gs://rixo-jdbc-europe-west2/temp"
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.TRANSACTION_LINE_BOOK_MAP`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.ITEM_PRICE_HISTORY`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.OPPORTUNITY_LINES`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.TRANSACTION_LINES`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.TRANSACTION_HISTORY`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.ITEM_LOCATION_MAP`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.TRANSACTION_LINKS`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.TRANSACTION_BIN_NUMBERS`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.POSTING_ACCOUNT_ACTIVITY`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.POSTING_ACCOUNT_ACTIVITY_PE`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.ITEM_PRICES`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.TRANSACTION_TAX_DETAIL`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.TRANSACTION_BOOK_MAP`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.ADDRESSES`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.TRANSACTIONS`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.TRANSACTION_ADDRESS`'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.TRANSACTION_LINE_BOOK_MAP` as select * from  `project-x-ray.netsuite_jdbc.TRANSACTION_LINE_BOOK_MAP_LOAD`'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.ITEM_PRICE_HISTORY` as select * from  `project-x-ray.netsuite_jdbc.ITEM_PRICE_HISTORY_LOAD`'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.OPPORTUNITY_LINES` as select * from  `project-x-ray.netsuite_jdbc.OPPORTUNITY_LINES_LOAD`'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.TRANSACTION_LINES` as select * from  `project-x-ray.netsuite_jdbc.TRANSACTION_LINES_LOAD`'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.TRANSACTION_HISTORY` as select * from  `project-x-ray.netsuite_jdbc.TRANSACTION_HISTORY_LOAD`'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.ITEM_LOCATION_MAP` as select * from  `project-x-ray.netsuite_jdbc.ITEM_LOCATION_MAP_LOAD`'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.TRANSACTION_LINKS` as select * from  `project-x-ray.netsuite_jdbc.TRANSACTION_LINKS_LOAD`'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.TRANSACTION_BIN_NUMBERS` as select * from  `project-x-ray.netsuite_jdbc.TRANSACTION_BIN_NUMBERS_LOAD`'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.POSTING_ACCOUNT_ACTIVITY` as select * from  `project-x-ray.netsuite_jdbc.POSTING_ACCOUNT_ACTIVITY_LOAD`'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.POSTING_ACCOUNT_ACTIVITY_PE` as select * from  `project-x-ray.netsuite_jdbc.POSTING_ACCOUNT_ACTIVITY_PE_LOAD`'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.ITEM_PRICES` as select * from  `project-x-ray.netsuite_jdbc.ITEM_PRICES_LOAD`'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.TRANSACTION_TAX_DETAIL` as select * from  `project-x-ray.netsuite_jdbc.TRANSACTION_TAX_DETAIL_LOAD`'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.TRANSACTION_BOOK_MAP` as select * from  `project-x-ray.netsuite_jdbc.TRANSACTION_BOOK_MAP_LOAD`'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.ADDRESSES` as select * from  `project-x-ray.netsuite_jdbc.ADDRESSES_LOAD`'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.TRANSACTIONS` as select * from  `project-x-ray.netsuite_jdbc.TRANSACTIONS_LOAD`'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.TRANSACTION_ADDRESS` as select * from  `project-x-ray.netsuite_jdbc.TRANSACTION_ADDRESS_LOAD`'
sleep 300
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.WMS_LABEL_PRINTING_LOAD`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.TRANSACTION_SHIPPING_GROUPS_LOAD`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.TRANSACTION_TRACKING_NUMBERS_LOAD`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.WMS_OPEN_TASK_LOAD`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.BIN_NUMBER_COUNTS_LOAD`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.05SIZE_MAP_LOAD`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.ITEMS_LOAD`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.ITEM_SUBSIDIARY_MAP_LOAD`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.FARAPP_SYNCED_ITEMS_LOAD`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.SUPPLIER_CATEGORIES_LOAD`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.INVENTORY_ITEMS_LOAD`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.02STYLE_NAME_MAP_LOAD`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.ITEM_VENDOR_MAP_LOAD`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.04PRINT_MAP_LOAD`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.03SEASON_MAP_LOAD`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.SHIPMENT_PACKAGES_LOAD`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.ROLES1_LOAD`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.ADDRESS_BOOK_LOAD`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.ITEM_VENDOR_PRICING_LOAD`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.ENTITY_LOAD`'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.WMS_LABEL_PRINTING_LOAD` as select * from  `project-x-ray.netsuite_ddl.WMS_LABEL_PRINTING` where false'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.TRANSACTION_SHIPPING_GROUPS_LOAD` as select * from  `project-x-ray.netsuite_ddl.TRANSACTION_SHIPPING_GROUPS` where false'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.TRANSACTION_TRACKING_NUMBERS_LOAD` as select * from  `project-x-ray.netsuite_ddl.TRANSACTION_TRACKING_NUMBERS` where false'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.WMS_OPEN_TASK_LOAD` as select * from  `project-x-ray.netsuite_ddl.WMS_OPEN_TASK` where false'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.BIN_NUMBER_COUNTS_LOAD` as select * from  `project-x-ray.netsuite_ddl.BIN_NUMBER_COUNTS` where false'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.05SIZE_MAP_LOAD` as select * from  `project-x-ray.netsuite_ddl.05SIZE_MAP` where false'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.ITEMS_LOAD` as select * from  `project-x-ray.netsuite_ddl.ITEMS` where false'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.ITEM_SUBSIDIARY_MAP_LOAD` as select * from  `project-x-ray.netsuite_ddl.ITEM_SUBSIDIARY_MAP` where false'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.FARAPP_SYNCED_ITEMS_LOAD` as select * from  `project-x-ray.netsuite_ddl.FARAPP_SYNCED_ITEMS` where false'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.SUPPLIER_CATEGORIES_LOAD` as select * from  `project-x-ray.netsuite_ddl.SUPPLIER_CATEGORIES` where false'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.INVENTORY_ITEMS_LOAD` as select * from  `project-x-ray.netsuite_ddl.INVENTORY_ITEMS` where false'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.02STYLE_NAME_MAP_LOAD` as select * from  `project-x-ray.netsuite_ddl.02STYLE_NAME_MAP` where false'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.ITEM_VENDOR_MAP_LOAD` as select * from  `project-x-ray.netsuite_ddl.ITEM_VENDOR_MAP` where false'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.04PRINT_MAP_LOAD` as select * from  `project-x-ray.netsuite_ddl.04PRINT_MAP` where false'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.03SEASON_MAP_LOAD` as select * from  `project-x-ray.netsuite_ddl.03SEASON_MAP` where false'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.SHIPMENT_PACKAGES_LOAD` as select * from  `project-x-ray.netsuite_ddl.SHIPMENT_PACKAGES` where false'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.ROLES1_LOAD` as select * from  `project-x-ray.netsuite_ddl.ROLES1` where false'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.ADDRESS_BOOK_LOAD` as select * from  `project-x-ray.netsuite_ddl.ADDRESS_BOOK` where false'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.ITEM_VENDOR_PRICING_LOAD` as select * from  `project-x-ray.netsuite_ddl.ITEM_VENDOR_PRICING` where false'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.ENTITY_LOAD` as select * from  `project-x-ray.netsuite_ddl.ENTITY` where false'
nohup gcloud dataflow jobs run copy_WMS_LABEL_PRINTING --project=project-x-ray --region europe-west2 --gcs-location gs://dataflow-templates-europe-west2/latest/Jdbc_to_BigQuery --parameters query="select * from WMS_LABEL_PRINTING",connectionURL="jdbc:ns://5514691.connect.api.netsuite.com:1708;ServerDataSource=NetSuite.com;encrypted=1;Ciphersuites=Ciphersuites=TLS_RSA_WITH_AES_128_CBC_SHA;CustomProperties=(AccountID=5514691;RoleID=1057)",username="mark.rittman@rittmananalytics.com",password="Rittman123",driverClassName="com.netsuite.jdbc.openaccess.OpenAccessDriver",driverJars="gs://rixo-jdbc-europe-west2/NQjc.jar",outputTable="project-x-ray:netsuite_jdbc.WMS_LABEL_PRINTING_LOAD",bigQueryLoadingTemporaryDirectory="gs://rixo-jdbc-europe-west2/temp"
nohup gcloud dataflow jobs run copy_TRANSACTION_SHIPPING_GROUPS --project=project-x-ray --region europe-west2 --gcs-location gs://dataflow-templates-europe-west2/latest/Jdbc_to_BigQuery --parameters query="select * from TRANSACTION_SHIPPING_GROUPS",connectionURL="jdbc:ns://5514691.connect.api.netsuite.com:1708;ServerDataSource=NetSuite.com;encrypted=1;Ciphersuites=Ciphersuites=TLS_RSA_WITH_AES_128_CBC_SHA;CustomProperties=(AccountID=5514691;RoleID=1057)",username="mark.rittman@rittmananalytics.com",password="Rittman123",driverClassName="com.netsuite.jdbc.openaccess.OpenAccessDriver",driverJars="gs://rixo-jdbc-europe-west2/NQjc.jar",outputTable="project-x-ray:netsuite_jdbc.TRANSACTION_SHIPPING_GROUPS_LOAD",bigQueryLoadingTemporaryDirectory="gs://rixo-jdbc-europe-west2/temp"
nohup gcloud dataflow jobs run copy_TRANSACTION_TRACKING_NUMBERS --project=project-x-ray --region europe-west2 --gcs-location gs://dataflow-templates-europe-west2/latest/Jdbc_to_BigQuery --parameters query="select * from TRANSACTION_TRACKING_NUMBERS",connectionURL="jdbc:ns://5514691.connect.api.netsuite.com:1708;ServerDataSource=NetSuite.com;encrypted=1;Ciphersuites=Ciphersuites=TLS_RSA_WITH_AES_128_CBC_SHA;CustomProperties=(AccountID=5514691;RoleID=1057)",username="mark.rittman@rittmananalytics.com",password="Rittman123",driverClassName="com.netsuite.jdbc.openaccess.OpenAccessDriver",driverJars="gs://rixo-jdbc-europe-west2/NQjc.jar",outputTable="project-x-ray:netsuite_jdbc.TRANSACTION_TRACKING_NUMBERS_LOAD",bigQueryLoadingTemporaryDirectory="gs://rixo-jdbc-europe-west2/temp"
nohup gcloud dataflow jobs run copy_WMS_OPEN_TASK --project=project-x-ray --region europe-west2 --gcs-location gs://dataflow-templates-europe-west2/latest/Jdbc_to_BigQuery --parameters query="select * from WMS_OPEN_TASK",connectionURL="jdbc:ns://5514691.connect.api.netsuite.com:1708;ServerDataSource=NetSuite.com;encrypted=1;Ciphersuites=Ciphersuites=TLS_RSA_WITH_AES_128_CBC_SHA;CustomProperties=(AccountID=5514691;RoleID=1057)",username="mark.rittman@rittmananalytics.com",password="Rittman123",driverClassName="com.netsuite.jdbc.openaccess.OpenAccessDriver",driverJars="gs://rixo-jdbc-europe-west2/NQjc.jar",outputTable="project-x-ray:netsuite_jdbc.WMS_OPEN_TASK_LOAD",bigQueryLoadingTemporaryDirectory="gs://rixo-jdbc-europe-west2/temp"
nohup gcloud dataflow jobs run copy_BIN_NUMBER_COUNTS --project=project-x-ray --region europe-west2 --gcs-location gs://dataflow-templates-europe-west2/latest/Jdbc_to_BigQuery --parameters query="select * from BIN_NUMBER_COUNTS",connectionURL="jdbc:ns://5514691.connect.api.netsuite.com:1708;ServerDataSource=NetSuite.com;encrypted=1;Ciphersuites=Ciphersuites=TLS_RSA_WITH_AES_128_CBC_SHA;CustomProperties=(AccountID=5514691;RoleID=1057)",username="mark.rittman@rittmananalytics.com",password="Rittman123",driverClassName="com.netsuite.jdbc.openaccess.OpenAccessDriver",driverJars="gs://rixo-jdbc-europe-west2/NQjc.jar",outputTable="project-x-ray:netsuite_jdbc.BIN_NUMBER_COUNTS_LOAD",bigQueryLoadingTemporaryDirectory="gs://rixo-jdbc-europe-west2/temp"
nohup gcloud dataflow jobs run copy_05SIZE_MAP --project=project-x-ray --region europe-west2 --gcs-location gs://dataflow-templates-europe-west2/latest/Jdbc_to_BigQuery --parameters query="select * from 05SIZE_MAP",connectionURL="jdbc:ns://5514691.connect.api.netsuite.com:1708;ServerDataSource=NetSuite.com;encrypted=1;Ciphersuites=Ciphersuites=TLS_RSA_WITH_AES_128_CBC_SHA;CustomProperties=(AccountID=5514691;RoleID=1057)",username="mark.rittman@rittmananalytics.com",password="Rittman123",driverClassName="com.netsuite.jdbc.openaccess.OpenAccessDriver",driverJars="gs://rixo-jdbc-europe-west2/NQjc.jar",outputTable="project-x-ray:netsuite_jdbc.05SIZE_MAP_LOAD",bigQueryLoadingTemporaryDirectory="gs://rixo-jdbc-europe-west2/temp"
nohup gcloud dataflow jobs run copy_ITEMS --project=project-x-ray --region europe-west2 --gcs-location gs://dataflow-templates-europe-west2/latest/Jdbc_to_BigQuery --parameters query="select * from ITEMS",connectionURL="jdbc:ns://5514691.connect.api.netsuite.com:1708;ServerDataSource=NetSuite.com;encrypted=1;Ciphersuites=Ciphersuites=TLS_RSA_WITH_AES_128_CBC_SHA;CustomProperties=(AccountID=5514691;RoleID=1057)",username="mark.rittman@rittmananalytics.com",password="Rittman123",driverClassName="com.netsuite.jdbc.openaccess.OpenAccessDriver",driverJars="gs://rixo-jdbc-europe-west2/NQjc.jar",outputTable="project-x-ray:netsuite_jdbc.ITEMS_LOAD",bigQueryLoadingTemporaryDirectory="gs://rixo-jdbc-europe-west2/temp"
nohup gcloud dataflow jobs run copy_ITEM_SUBSIDIARY_MAP --project=project-x-ray --region europe-west2 --gcs-location gs://dataflow-templates-europe-west2/latest/Jdbc_to_BigQuery --parameters query="select * from ITEM_SUBSIDIARY_MAP",connectionURL="jdbc:ns://5514691.connect.api.netsuite.com:1708;ServerDataSource=NetSuite.com;encrypted=1;Ciphersuites=Ciphersuites=TLS_RSA_WITH_AES_128_CBC_SHA;CustomProperties=(AccountID=5514691;RoleID=1057)",username="mark.rittman@rittmananalytics.com",password="Rittman123",driverClassName="com.netsuite.jdbc.openaccess.OpenAccessDriver",driverJars="gs://rixo-jdbc-europe-west2/NQjc.jar",outputTable="project-x-ray:netsuite_jdbc.ITEM_SUBSIDIARY_MAP_LOAD",bigQueryLoadingTemporaryDirectory="gs://rixo-jdbc-europe-west2/temp"
nohup gcloud dataflow jobs run copy_FARAPP_SYNCED_ITEMS --project=project-x-ray --region europe-west2 --gcs-location gs://dataflow-templates-europe-west2/latest/Jdbc_to_BigQuery --parameters query="select * from FARAPP_SYNCED_ITEMS",connectionURL="jdbc:ns://5514691.connect.api.netsuite.com:1708;ServerDataSource=NetSuite.com;encrypted=1;Ciphersuites=Ciphersuites=TLS_RSA_WITH_AES_128_CBC_SHA;CustomProperties=(AccountID=5514691;RoleID=1057)",username="mark.rittman@rittmananalytics.com",password="Rittman123",driverClassName="com.netsuite.jdbc.openaccess.OpenAccessDriver",driverJars="gs://rixo-jdbc-europe-west2/NQjc.jar",outputTable="project-x-ray:netsuite_jdbc.FARAPP_SYNCED_ITEMS_LOAD",bigQueryLoadingTemporaryDirectory="gs://rixo-jdbc-europe-west2/temp"
nohup gcloud dataflow jobs run copy_SUPPLIER_CATEGORIES --project=project-x-ray --region europe-west2 --gcs-location gs://dataflow-templates-europe-west2/latest/Jdbc_to_BigQuery --parameters query="select * from SUPPLIER_CATEGORIES",connectionURL="jdbc:ns://5514691.connect.api.netsuite.com:1708;ServerDataSource=NetSuite.com;encrypted=1;Ciphersuites=Ciphersuites=TLS_RSA_WITH_AES_128_CBC_SHA;CustomProperties=(AccountID=5514691;RoleID=1057)",username="mark.rittman@rittmananalytics.com",password="Rittman123",driverClassName="com.netsuite.jdbc.openaccess.OpenAccessDriver",driverJars="gs://rixo-jdbc-europe-west2/NQjc.jar",outputTable="project-x-ray:netsuite_jdbc.SUPPLIER_CATEGORIES_LOAD",bigQueryLoadingTemporaryDirectory="gs://rixo-jdbc-europe-west2/temp"
nohup gcloud dataflow jobs run copy_INVENTORY_ITEMS --project=project-x-ray --region europe-west2 --gcs-location gs://dataflow-templates-europe-west2/latest/Jdbc_to_BigQuery --parameters query="select * from INVENTORY_ITEMS",connectionURL="jdbc:ns://5514691.connect.api.netsuite.com:1708;ServerDataSource=NetSuite.com;encrypted=1;Ciphersuites=Ciphersuites=TLS_RSA_WITH_AES_128_CBC_SHA;CustomProperties=(AccountID=5514691;RoleID=1057)",username="mark.rittman@rittmananalytics.com",password="Rittman123",driverClassName="com.netsuite.jdbc.openaccess.OpenAccessDriver",driverJars="gs://rixo-jdbc-europe-west2/NQjc.jar",outputTable="project-x-ray:netsuite_jdbc.INVENTORY_ITEMS_LOAD",bigQueryLoadingTemporaryDirectory="gs://rixo-jdbc-europe-west2/temp"
nohup gcloud dataflow jobs run copy_02STYLE_NAME_MAP --project=project-x-ray --region europe-west2 --gcs-location gs://dataflow-templates-europe-west2/latest/Jdbc_to_BigQuery --parameters query="select * from 02STYLE_NAME_MAP",connectionURL="jdbc:ns://5514691.connect.api.netsuite.com:1708;ServerDataSource=NetSuite.com;encrypted=1;Ciphersuites=Ciphersuites=TLS_RSA_WITH_AES_128_CBC_SHA;CustomProperties=(AccountID=5514691;RoleID=1057)",username="mark.rittman@rittmananalytics.com",password="Rittman123",driverClassName="com.netsuite.jdbc.openaccess.OpenAccessDriver",driverJars="gs://rixo-jdbc-europe-west2/NQjc.jar",outputTable="project-x-ray:netsuite_jdbc.02STYLE_NAME_MAP_LOAD",bigQueryLoadingTemporaryDirectory="gs://rixo-jdbc-europe-west2/temp"
nohup gcloud dataflow jobs run copy_ITEM_VENDOR_MAP --project=project-x-ray --region europe-west2 --gcs-location gs://dataflow-templates-europe-west2/latest/Jdbc_to_BigQuery --parameters query="select * from ITEM_VENDOR_MAP",connectionURL="jdbc:ns://5514691.connect.api.netsuite.com:1708;ServerDataSource=NetSuite.com;encrypted=1;Ciphersuites=Ciphersuites=TLS_RSA_WITH_AES_128_CBC_SHA;CustomProperties=(AccountID=5514691;RoleID=1057)",username="mark.rittman@rittmananalytics.com",password="Rittman123",driverClassName="com.netsuite.jdbc.openaccess.OpenAccessDriver",driverJars="gs://rixo-jdbc-europe-west2/NQjc.jar",outputTable="project-x-ray:netsuite_jdbc.ITEM_VENDOR_MAP_LOAD",bigQueryLoadingTemporaryDirectory="gs://rixo-jdbc-europe-west2/temp"
nohup gcloud dataflow jobs run copy_04PRINT_MAP --project=project-x-ray --region europe-west2 --gcs-location gs://dataflow-templates-europe-west2/latest/Jdbc_to_BigQuery --parameters query="select * from 04PRINT_MAP",connectionURL="jdbc:ns://5514691.connect.api.netsuite.com:1708;ServerDataSource=NetSuite.com;encrypted=1;Ciphersuites=Ciphersuites=TLS_RSA_WITH_AES_128_CBC_SHA;CustomProperties=(AccountID=5514691;RoleID=1057)",username="mark.rittman@rittmananalytics.com",password="Rittman123",driverClassName="com.netsuite.jdbc.openaccess.OpenAccessDriver",driverJars="gs://rixo-jdbc-europe-west2/NQjc.jar",outputTable="project-x-ray:netsuite_jdbc.04PRINT_MAP_LOAD",bigQueryLoadingTemporaryDirectory="gs://rixo-jdbc-europe-west2/temp"
nohup gcloud dataflow jobs run copy_03SEASON_MAP --project=project-x-ray --region europe-west2 --gcs-location gs://dataflow-templates-europe-west2/latest/Jdbc_to_BigQuery --parameters query="select * from 03SEASON_MAP",connectionURL="jdbc:ns://5514691.connect.api.netsuite.com:1708;ServerDataSource=NetSuite.com;encrypted=1;Ciphersuites=Ciphersuites=TLS_RSA_WITH_AES_128_CBC_SHA;CustomProperties=(AccountID=5514691;RoleID=1057)",username="mark.rittman@rittmananalytics.com",password="Rittman123",driverClassName="com.netsuite.jdbc.openaccess.OpenAccessDriver",driverJars="gs://rixo-jdbc-europe-west2/NQjc.jar",outputTable="project-x-ray:netsuite_jdbc.03SEASON_MAP_LOAD",bigQueryLoadingTemporaryDirectory="gs://rixo-jdbc-europe-west2/temp"
nohup gcloud dataflow jobs run copy_SHIPMENT_PACKAGES --project=project-x-ray --region europe-west2 --gcs-location gs://dataflow-templates-europe-west2/latest/Jdbc_to_BigQuery --parameters query="select * from SHIPMENT_PACKAGES",connectionURL="jdbc:ns://5514691.connect.api.netsuite.com:1708;ServerDataSource=NetSuite.com;encrypted=1;Ciphersuites=Ciphersuites=TLS_RSA_WITH_AES_128_CBC_SHA;CustomProperties=(AccountID=5514691;RoleID=1057)",username="mark.rittman@rittmananalytics.com",password="Rittman123",driverClassName="com.netsuite.jdbc.openaccess.OpenAccessDriver",driverJars="gs://rixo-jdbc-europe-west2/NQjc.jar",outputTable="project-x-ray:netsuite_jdbc.SHIPMENT_PACKAGES_LOAD",bigQueryLoadingTemporaryDirectory="gs://rixo-jdbc-europe-west2/temp"
nohup gcloud dataflow jobs run copy_ROLES1 --project=project-x-ray --region europe-west2 --gcs-location gs://dataflow-templates-europe-west2/latest/Jdbc_to_BigQuery --parameters query="select * from ROLES1",connectionURL="jdbc:ns://5514691.connect.api.netsuite.com:1708;ServerDataSource=NetSuite.com;encrypted=1;Ciphersuites=Ciphersuites=TLS_RSA_WITH_AES_128_CBC_SHA;CustomProperties=(AccountID=5514691;RoleID=1057)",username="mark.rittman@rittmananalytics.com",password="Rittman123",driverClassName="com.netsuite.jdbc.openaccess.OpenAccessDriver",driverJars="gs://rixo-jdbc-europe-west2/NQjc.jar",outputTable="project-x-ray:netsuite_jdbc.ROLES1_LOAD",bigQueryLoadingTemporaryDirectory="gs://rixo-jdbc-europe-west2/temp"
nohup gcloud dataflow jobs run copy_ADDRESS_BOOK --project=project-x-ray --region europe-west2 --gcs-location gs://dataflow-templates-europe-west2/latest/Jdbc_to_BigQuery --parameters query="select * from ADDRESS_BOOK",connectionURL="jdbc:ns://5514691.connect.api.netsuite.com:1708;ServerDataSource=NetSuite.com;encrypted=1;Ciphersuites=Ciphersuites=TLS_RSA_WITH_AES_128_CBC_SHA;CustomProperties=(AccountID=5514691;RoleID=1057)",username="mark.rittman@rittmananalytics.com",password="Rittman123",driverClassName="com.netsuite.jdbc.openaccess.OpenAccessDriver",driverJars="gs://rixo-jdbc-europe-west2/NQjc.jar",outputTable="project-x-ray:netsuite_jdbc.ADDRESS_BOOK_LOAD",bigQueryLoadingTemporaryDirectory="gs://rixo-jdbc-europe-west2/temp"
nohup gcloud dataflow jobs run copy_ITEM_VENDOR_PRICING --project=project-x-ray --region europe-west2 --gcs-location gs://dataflow-templates-europe-west2/latest/Jdbc_to_BigQuery --parameters query="select * from ITEM_VENDOR_PRICING",connectionURL="jdbc:ns://5514691.connect.api.netsuite.com:1708;ServerDataSource=NetSuite.com;encrypted=1;Ciphersuites=Ciphersuites=TLS_RSA_WITH_AES_128_CBC_SHA;CustomProperties=(AccountID=5514691;RoleID=1057)",username="mark.rittman@rittmananalytics.com",password="Rittman123",driverClassName="com.netsuite.jdbc.openaccess.OpenAccessDriver",driverJars="gs://rixo-jdbc-europe-west2/NQjc.jar",outputTable="project-x-ray:netsuite_jdbc.ITEM_VENDOR_PRICING_LOAD",bigQueryLoadingTemporaryDirectory="gs://rixo-jdbc-europe-west2/temp"
nohup gcloud dataflow jobs run copy_ENTITY --project=project-x-ray --region europe-west2 --gcs-location gs://dataflow-templates-europe-west2/latest/Jdbc_to_BigQuery --parameters query="select * from ENTITY",connectionURL="jdbc:ns://5514691.connect.api.netsuite.com:1708;ServerDataSource=NetSuite.com;encrypted=1;Ciphersuites=Ciphersuites=TLS_RSA_WITH_AES_128_CBC_SHA;CustomProperties=(AccountID=5514691;RoleID=1057)",username="mark.rittman@rittmananalytics.com",password="Rittman123",driverClassName="com.netsuite.jdbc.openaccess.OpenAccessDriver",driverJars="gs://rixo-jdbc-europe-west2/NQjc.jar",outputTable="project-x-ray:netsuite_jdbc.ENTITY_LOAD",bigQueryLoadingTemporaryDirectory="gs://rixo-jdbc-europe-west2/temp"
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.WMS_LABEL_PRINTING`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.TRANSACTION_SHIPPING_GROUPS`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.TRANSACTION_TRACKING_NUMBERS`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.WMS_OPEN_TASK`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.BIN_NUMBER_COUNTS`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.05SIZE_MAP`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.ITEMS`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.ITEM_SUBSIDIARY_MAP`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.FARAPP_SYNCED_ITEMS`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.SUPPLIER_CATEGORIES`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.INVENTORY_ITEMS`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.02STYLE_NAME_MAP`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.ITEM_VENDOR_MAP`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.04PRINT_MAP`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.03SEASON_MAP`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.SHIPMENT_PACKAGES`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.ROLES1`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.ADDRESS_BOOK`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.ITEM_VENDOR_PRICING`'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.WMS_LABEL_PRINTING` as select * from  `project-x-ray.netsuite_jdbc.WMS_LABEL_PRINTING_LOAD`'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.TRANSACTION_SHIPPING_GROUPS` as select * from  `project-x-ray.netsuite_jdbc.TRANSACTION_SHIPPING_GROUPS_LOAD`'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.TRANSACTION_TRACKING_NUMBERS` as select * from  `project-x-ray.netsuite_jdbc.TRANSACTION_TRACKING_NUMBERS_LOAD`'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.WMS_OPEN_TASK` as select * from  `project-x-ray.netsuite_jdbc.WMS_OPEN_TASK_LOAD`'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.BIN_NUMBER_COUNTS` as select * from  `project-x-ray.netsuite_jdbc.BIN_NUMBER_COUNTS_LOAD`'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.05SIZE_MAP` as select * from  `project-x-ray.netsuite_jdbc.05SIZE_MAP_LOAD`'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.ITEMS` as select * from  `project-x-ray.netsuite_jdbc.ITEMS_LOAD`'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.ITEM_SUBSIDIARY_MAP` as select * from  `project-x-ray.netsuite_jdbc.ITEM_SUBSIDIARY_MAP_LOAD`'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.FARAPP_SYNCED_ITEMS` as select * from  `project-x-ray.netsuite_jdbc.FARAPP_SYNCED_ITEMS_LOAD`'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.SUPPLIER_CATEGORIES` as select * from  `project-x-ray.netsuite_jdbc.SUPPLIER_CATEGORIES_LOAD`'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.INVENTORY_ITEMS` as select * from  `project-x-ray.netsuite_jdbc.INVENTORY_ITEMS_LOAD`'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.02STYLE_NAME_MAP` as select * from  `project-x-ray.netsuite_jdbc.02STYLE_NAME_MAP_LOAD`'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.ITEM_VENDOR_MAP` as select * from  `project-x-ray.netsuite_jdbc.ITEM_VENDOR_MAP_LOAD`'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.04PRINT_MAP` as select * from  `project-x-ray.netsuite_jdbc.04PRINT_MAP_LOAD`'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.03SEASON_MAP` as select * from  `project-x-ray.netsuite_jdbc.03SEASON_MAP_LOAD`'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.SHIPMENT_PACKAGES` as select * from  `project-x-ray.netsuite_jdbc.SHIPMENT_PACKAGES_LOAD`'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.ROLES1` as select * from  `project-x-ray.netsuite_jdbc.ROLES1_LOAD`'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.ADDRESS_BOOK` as select * from  `project-x-ray.netsuite_jdbc.ADDRESS_BOOK_LOAD`'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.ITEM_VENDOR_PRICING` as select * from  `project-x-ray.netsuite_jdbc.ITEM_VENDOR_PRICING_LOAD`'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.ENTITY` as select * from  `project-x-ray.netsuite_jdbc.ENTITY_LOAD`'
sleep 300
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.ITEM_FULFILLMENTS_LOAD`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.COMPANIES_LOAD`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.WMS_EXTERNAL_LABEL_DETAILS_LOAD`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.WMS_SHIP_MANIFEST_LOAD`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.CUSTOMER_CURRENCIES_LOAD`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.ENTITY_STATUS_HISTORY_LOAD`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.CUSTOMER_SUBSIDIARY_MAP_LOAD`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.CUSTOMERS_LOAD`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.WMS_SERIAL_ENTRY_LOAD`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.CLIENT_AUDIT_TRAIL_LOAD`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.WMS_COMMODITY_SHIPMENT_LOAD`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.INBOUND_SHIPMENT_ITEMS_LOAD`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.CYCLE_COUNT_PLAN_BINS_MAP_LOAD`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.CONTACTS_LOAD`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.VENDORS_LOAD`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.CYCLE_COUNT_PLAN_ITEM_MAP_LOAD`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.COUPON_CODES_LOAD`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.INBOUND_SHIPMENTS_LOAD`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.PROMOTION_CODES_LOAD`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.EMPLOYEES_LOAD`'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.ITEM_FULFILLMENTS_LOAD` as select * from  `project-x-ray.netsuite_ddl.ITEM_FULFILLMENTS` where false'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.COMPANIES_LOAD` as select * from  `project-x-ray.netsuite_ddl.COMPANIES` where false'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.WMS_EXTERNAL_LABEL_DETAILS_LOAD` as select * from  `project-x-ray.netsuite_ddl.WMS_EXTERNAL_LABEL_DETAILS` where false'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.WMS_SHIP_MANIFEST_LOAD` as select * from  `project-x-ray.netsuite_ddl.WMS_SHIP_MANIFEST` where false'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.CUSTOMER_CURRENCIES_LOAD` as select * from  `project-x-ray.netsuite_ddl.CUSTOMER_CURRENCIES` where false'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.ENTITY_STATUS_HISTORY_LOAD` as select * from  `project-x-ray.netsuite_ddl.ENTITY_STATUS_HISTORY` where false'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.CUSTOMER_SUBSIDIARY_MAP_LOAD` as select * from  `project-x-ray.netsuite_ddl.CUSTOMER_SUBSIDIARY_MAP` where false'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.CUSTOMERS_LOAD` as select * from  `project-x-ray.netsuite_ddl.CUSTOMERS` where false'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.WMS_SERIAL_ENTRY_LOAD` as select * from  `project-x-ray.netsuite_ddl.WMS_SERIAL_ENTRY` where false'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.CLIENT_AUDIT_TRAIL_LOAD` as select * from  `project-x-ray.netsuite_ddl.CLIENT_AUDIT_TRAIL` where false'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.WMS_COMMODITY_SHIPMENT_LOAD` as select * from  `project-x-ray.netsuite_ddl.WMS_COMMODITY_SHIPMENT` where false'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.INBOUND_SHIPMENT_ITEMS_LOAD` as select * from  `project-x-ray.netsuite_ddl.INBOUND_SHIPMENT_ITEMS` where false'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.CYCLE_COUNT_PLAN_BINS_MAP_LOAD` as select * from  `project-x-ray.netsuite_ddl.CYCLE_COUNT_PLAN_BINS_MAP` where false'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.CONTACTS_LOAD` as select * from  `project-x-ray.netsuite_ddl.CONTACTS` where false'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.VENDORS_LOAD` as select * from  `project-x-ray.netsuite_ddl.VENDORS` where false'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.CYCLE_COUNT_PLAN_ITEM_MAP_LOAD` as select * from  `project-x-ray.netsuite_ddl.CYCLE_COUNT_PLAN_ITEM_MAP` where false'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.COUPON_CODES_LOAD` as select * from  `project-x-ray.netsuite_ddl.COUPON_CODES` where false'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.INBOUND_SHIPMENTS_LOAD` as select * from  `project-x-ray.netsuite_ddl.INBOUND_SHIPMENTS` where false'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.PROMOTION_CODES_LOAD` as select * from  `project-x-ray.netsuite_ddl.PROMOTION_CODES` where false'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.EMPLOYEES_LOAD` as select * from  `project-x-ray.netsuite_ddl.EMPLOYEES` where false'
nohup gcloud dataflow jobs run copy_ITEM_FULFILLMENTS --project=project-x-ray --region europe-west2 --gcs-location gs://dataflow-templates-europe-west2/latest/Jdbc_to_BigQuery --parameters query="select * from ITEM_FULFILLMENTS",connectionURL="jdbc:ns://5514691.connect.api.netsuite.com:1708;ServerDataSource=NetSuite.com;encrypted=1;Ciphersuites=Ciphersuites=TLS_RSA_WITH_AES_128_CBC_SHA;CustomProperties=(AccountID=5514691;RoleID=1057)",username="mark.rittman@rittmananalytics.com",password="Rittman123",driverClassName="com.netsuite.jdbc.openaccess.OpenAccessDriver",driverJars="gs://rixo-jdbc-europe-west2/NQjc.jar",outputTable="project-x-ray:netsuite_jdbc.ITEM_FULFILLMENTS_LOAD",bigQueryLoadingTemporaryDirectory="gs://rixo-jdbc-europe-west2/temp"
nohup gcloud dataflow jobs run copy_COMPANIES --project=project-x-ray --region europe-west2 --gcs-location gs://dataflow-templates-europe-west2/latest/Jdbc_to_BigQuery --parameters query="select * from COMPANIES",connectionURL="jdbc:ns://5514691.connect.api.netsuite.com:1708;ServerDataSource=NetSuite.com;encrypted=1;Ciphersuites=Ciphersuites=TLS_RSA_WITH_AES_128_CBC_SHA;CustomProperties=(AccountID=5514691;RoleID=1057)",username="mark.rittman@rittmananalytics.com",password="Rittman123",driverClassName="com.netsuite.jdbc.openaccess.OpenAccessDriver",driverJars="gs://rixo-jdbc-europe-west2/NQjc.jar",outputTable="project-x-ray:netsuite_jdbc.COMPANIES_LOAD",bigQueryLoadingTemporaryDirectory="gs://rixo-jdbc-europe-west2/temp"
nohup gcloud dataflow jobs run copy_WMS_EXTERNAL_LABEL_DETAILS --project=project-x-ray --region europe-west2 --gcs-location gs://dataflow-templates-europe-west2/latest/Jdbc_to_BigQuery --parameters query="select * from WMS_EXTERNAL_LABEL_DETAILS",connectionURL="jdbc:ns://5514691.connect.api.netsuite.com:1708;ServerDataSource=NetSuite.com;encrypted=1;Ciphersuites=Ciphersuites=TLS_RSA_WITH_AES_128_CBC_SHA;CustomProperties=(AccountID=5514691;RoleID=1057)",username="mark.rittman@rittmananalytics.com",password="Rittman123",driverClassName="com.netsuite.jdbc.openaccess.OpenAccessDriver",driverJars="gs://rixo-jdbc-europe-west2/NQjc.jar",outputTable="project-x-ray:netsuite_jdbc.WMS_EXTERNAL_LABEL_DETAILS_LOAD",bigQueryLoadingTemporaryDirectory="gs://rixo-jdbc-europe-west2/temp"
nohup gcloud dataflow jobs run copy_WMS_SHIP_MANIFEST --project=project-x-ray --region europe-west2 --gcs-location gs://dataflow-templates-europe-west2/latest/Jdbc_to_BigQuery --parameters query="select * from WMS_SHIP_MANIFEST",connectionURL="jdbc:ns://5514691.connect.api.netsuite.com:1708;ServerDataSource=NetSuite.com;encrypted=1;Ciphersuites=Ciphersuites=TLS_RSA_WITH_AES_128_CBC_SHA;CustomProperties=(AccountID=5514691;RoleID=1057)",username="mark.rittman@rittmananalytics.com",password="Rittman123",driverClassName="com.netsuite.jdbc.openaccess.OpenAccessDriver",driverJars="gs://rixo-jdbc-europe-west2/NQjc.jar",outputTable="project-x-ray:netsuite_jdbc.WMS_SHIP_MANIFEST_LOAD",bigQueryLoadingTemporaryDirectory="gs://rixo-jdbc-europe-west2/temp"
nohup gcloud dataflow jobs run copy_CUSTOMER_CURRENCIES --project=project-x-ray --region europe-west2 --gcs-location gs://dataflow-templates-europe-west2/latest/Jdbc_to_BigQuery --parameters query="select * from CUSTOMER_CURRENCIES",connectionURL="jdbc:ns://5514691.connect.api.netsuite.com:1708;ServerDataSource=NetSuite.com;encrypted=1;Ciphersuites=Ciphersuites=TLS_RSA_WITH_AES_128_CBC_SHA;CustomProperties=(AccountID=5514691;RoleID=1057)",username="mark.rittman@rittmananalytics.com",password="Rittman123",driverClassName="com.netsuite.jdbc.openaccess.OpenAccessDriver",driverJars="gs://rixo-jdbc-europe-west2/NQjc.jar",outputTable="project-x-ray:netsuite_jdbc.CUSTOMER_CURRENCIES_LOAD",bigQueryLoadingTemporaryDirectory="gs://rixo-jdbc-europe-west2/temp"
nohup gcloud dataflow jobs run copy_ENTITY_STATUS_HISTORY --project=project-x-ray --region europe-west2 --gcs-location gs://dataflow-templates-europe-west2/latest/Jdbc_to_BigQuery --parameters query="select * from ENTITY_STATUS_HISTORY",connectionURL="jdbc:ns://5514691.connect.api.netsuite.com:1708;ServerDataSource=NetSuite.com;encrypted=1;Ciphersuites=Ciphersuites=TLS_RSA_WITH_AES_128_CBC_SHA;CustomProperties=(AccountID=5514691;RoleID=1057)",username="mark.rittman@rittmananalytics.com",password="Rittman123",driverClassName="com.netsuite.jdbc.openaccess.OpenAccessDriver",driverJars="gs://rixo-jdbc-europe-west2/NQjc.jar",outputTable="project-x-ray:netsuite_jdbc.ENTITY_STATUS_HISTORY_LOAD",bigQueryLoadingTemporaryDirectory="gs://rixo-jdbc-europe-west2/temp"
nohup gcloud dataflow jobs run copy_CUSTOMER_SUBSIDIARY_MAP --project=project-x-ray --region europe-west2 --gcs-location gs://dataflow-templates-europe-west2/latest/Jdbc_to_BigQuery --parameters query="select * from CUSTOMER_SUBSIDIARY_MAP",connectionURL="jdbc:ns://5514691.connect.api.netsuite.com:1708;ServerDataSource=NetSuite.com;encrypted=1;Ciphersuites=Ciphersuites=TLS_RSA_WITH_AES_128_CBC_SHA;CustomProperties=(AccountID=5514691;RoleID=1057)",username="mark.rittman@rittmananalytics.com",password="Rittman123",driverClassName="com.netsuite.jdbc.openaccess.OpenAccessDriver",driverJars="gs://rixo-jdbc-europe-west2/NQjc.jar",outputTable="project-x-ray:netsuite_jdbc.CUSTOMER_SUBSIDIARY_MAP_LOAD",bigQueryLoadingTemporaryDirectory="gs://rixo-jdbc-europe-west2/temp"
nohup gcloud dataflow jobs run copy_CUSTOMERS --project=project-x-ray --region europe-west2 --gcs-location gs://dataflow-templates-europe-west2/latest/Jdbc_to_BigQuery --parameters query="select * from CUSTOMERS",connectionURL="jdbc:ns://5514691.connect.api.netsuite.com:1708;ServerDataSource=NetSuite.com;encrypted=1;Ciphersuites=Ciphersuites=TLS_RSA_WITH_AES_128_CBC_SHA;CustomProperties=(AccountID=5514691;RoleID=1057)",username="mark.rittman@rittmananalytics.com",password="Rittman123",driverClassName="com.netsuite.jdbc.openaccess.OpenAccessDriver",driverJars="gs://rixo-jdbc-europe-west2/NQjc.jar",outputTable="project-x-ray:netsuite_jdbc.CUSTOMERS_LOAD",bigQueryLoadingTemporaryDirectory="gs://rixo-jdbc-europe-west2/temp"
nohup gcloud dataflow jobs run copy_WMS_SERIAL_ENTRY --project=project-x-ray --region europe-west2 --gcs-location gs://dataflow-templates-europe-west2/latest/Jdbc_to_BigQuery --parameters query="select * from WMS_SERIAL_ENTRY",connectionURL="jdbc:ns://5514691.connect.api.netsuite.com:1708;ServerDataSource=NetSuite.com;encrypted=1;Ciphersuites=Ciphersuites=TLS_RSA_WITH_AES_128_CBC_SHA;CustomProperties=(AccountID=5514691;RoleID=1057)",username="mark.rittman@rittmananalytics.com",password="Rittman123",driverClassName="com.netsuite.jdbc.openaccess.OpenAccessDriver",driverJars="gs://rixo-jdbc-europe-west2/NQjc.jar",outputTable="project-x-ray:netsuite_jdbc.WMS_SERIAL_ENTRY_LOAD",bigQueryLoadingTemporaryDirectory="gs://rixo-jdbc-europe-west2/temp"
nohup gcloud dataflow jobs run copy_CLIENT_AUDIT_TRAIL --project=project-x-ray --region europe-west2 --gcs-location gs://dataflow-templates-europe-west2/latest/Jdbc_to_BigQuery --parameters query="select * from CLIENT_AUDIT_TRAIL",connectionURL="jdbc:ns://5514691.connect.api.netsuite.com:1708;ServerDataSource=NetSuite.com;encrypted=1;Ciphersuites=Ciphersuites=TLS_RSA_WITH_AES_128_CBC_SHA;CustomProperties=(AccountID=5514691;RoleID=1057)",username="mark.rittman@rittmananalytics.com",password="Rittman123",driverClassName="com.netsuite.jdbc.openaccess.OpenAccessDriver",driverJars="gs://rixo-jdbc-europe-west2/NQjc.jar",outputTable="project-x-ray:netsuite_jdbc.CLIENT_AUDIT_TRAIL_LOAD",bigQueryLoadingTemporaryDirectory="gs://rixo-jdbc-europe-west2/temp"
nohup gcloud dataflow jobs run copy_WMS_COMMODITY_SHIPMENT --project=project-x-ray --region europe-west2 --gcs-location gs://dataflow-templates-europe-west2/latest/Jdbc_to_BigQuery --parameters query="select * from WMS_COMMODITY_SHIPMENT",connectionURL="jdbc:ns://5514691.connect.api.netsuite.com:1708;ServerDataSource=NetSuite.com;encrypted=1;Ciphersuites=Ciphersuites=TLS_RSA_WITH_AES_128_CBC_SHA;CustomProperties=(AccountID=5514691;RoleID=1057)",username="mark.rittman@rittmananalytics.com",password="Rittman123",driverClassName="com.netsuite.jdbc.openaccess.OpenAccessDriver",driverJars="gs://rixo-jdbc-europe-west2/NQjc.jar",outputTable="project-x-ray:netsuite_jdbc.WMS_COMMODITY_SHIPMENT_LOAD",bigQueryLoadingTemporaryDirectory="gs://rixo-jdbc-europe-west2/temp"
nohup gcloud dataflow jobs run copy_INBOUND_SHIPMENT_ITEMS --project=project-x-ray --region europe-west2 --gcs-location gs://dataflow-templates-europe-west2/latest/Jdbc_to_BigQuery --parameters query="select * from INBOUND_SHIPMENT_ITEMS",connectionURL="jdbc:ns://5514691.connect.api.netsuite.com:1708;ServerDataSource=NetSuite.com;encrypted=1;Ciphersuites=Ciphersuites=TLS_RSA_WITH_AES_128_CBC_SHA;CustomProperties=(AccountID=5514691;RoleID=1057)",username="mark.rittman@rittmananalytics.com",password="Rittman123",driverClassName="com.netsuite.jdbc.openaccess.OpenAccessDriver",driverJars="gs://rixo-jdbc-europe-west2/NQjc.jar",outputTable="project-x-ray:netsuite_jdbc.INBOUND_SHIPMENT_ITEMS_LOAD",bigQueryLoadingTemporaryDirectory="gs://rixo-jdbc-europe-west2/temp"
nohup gcloud dataflow jobs run copy_CYCLE_COUNT_PLAN_BINS_MAP --project=project-x-ray --region europe-west2 --gcs-location gs://dataflow-templates-europe-west2/latest/Jdbc_to_BigQuery --parameters query="select * from CYCLE_COUNT_PLAN_BINS_MAP",connectionURL="jdbc:ns://5514691.connect.api.netsuite.com:1708;ServerDataSource=NetSuite.com;encrypted=1;Ciphersuites=Ciphersuites=TLS_RSA_WITH_AES_128_CBC_SHA;CustomProperties=(AccountID=5514691;RoleID=1057)",username="mark.rittman@rittmananalytics.com",password="Rittman123",driverClassName="com.netsuite.jdbc.openaccess.OpenAccessDriver",driverJars="gs://rixo-jdbc-europe-west2/NQjc.jar",outputTable="project-x-ray:netsuite_jdbc.CYCLE_COUNT_PLAN_BINS_MAP_LOAD",bigQueryLoadingTemporaryDirectory="gs://rixo-jdbc-europe-west2/temp"
nohup gcloud dataflow jobs run copy_CONTACTS --project=project-x-ray --region europe-west2 --gcs-location gs://dataflow-templates-europe-west2/latest/Jdbc_to_BigQuery --parameters query="select * from CONTACTS",connectionURL="jdbc:ns://5514691.connect.api.netsuite.com:1708;ServerDataSource=NetSuite.com;encrypted=1;Ciphersuites=Ciphersuites=TLS_RSA_WITH_AES_128_CBC_SHA;CustomProperties=(AccountID=5514691;RoleID=1057)",username="mark.rittman@rittmananalytics.com",password="Rittman123",driverClassName="com.netsuite.jdbc.openaccess.OpenAccessDriver",driverJars="gs://rixo-jdbc-europe-west2/NQjc.jar",outputTable="project-x-ray:netsuite_jdbc.CONTACTS_LOAD",bigQueryLoadingTemporaryDirectory="gs://rixo-jdbc-europe-west2/temp"
nohup gcloud dataflow jobs run copy_VENDORS --project=project-x-ray --region europe-west2 --gcs-location gs://dataflow-templates-europe-west2/latest/Jdbc_to_BigQuery --parameters query="select * from VENDORS",connectionURL="jdbc:ns://5514691.connect.api.netsuite.com:1708;ServerDataSource=NetSuite.com;encrypted=1;Ciphersuites=Ciphersuites=TLS_RSA_WITH_AES_128_CBC_SHA;CustomProperties=(AccountID=5514691;RoleID=1057)",username="mark.rittman@rittmananalytics.com",password="Rittman123",driverClassName="com.netsuite.jdbc.openaccess.OpenAccessDriver",driverJars="gs://rixo-jdbc-europe-west2/NQjc.jar",outputTable="project-x-ray:netsuite_jdbc.VENDORS_LOAD",bigQueryLoadingTemporaryDirectory="gs://rixo-jdbc-europe-west2/temp"
nohup gcloud dataflow jobs run copy_CYCLE_COUNT_PLAN_ITEM_MAP --project=project-x-ray --region europe-west2 --gcs-location gs://dataflow-templates-europe-west2/latest/Jdbc_to_BigQuery --parameters query="select * from CYCLE_COUNT_PLAN_ITEM_MAP",connectionURL="jdbc:ns://5514691.connect.api.netsuite.com:1708;ServerDataSource=NetSuite.com;encrypted=1;Ciphersuites=Ciphersuites=TLS_RSA_WITH_AES_128_CBC_SHA;CustomProperties=(AccountID=5514691;RoleID=1057)",username="mark.rittman@rittmananalytics.com",password="Rittman123",driverClassName="com.netsuite.jdbc.openaccess.OpenAccessDriver",driverJars="gs://rixo-jdbc-europe-west2/NQjc.jar",outputTable="project-x-ray:netsuite_jdbc.CYCLE_COUNT_PLAN_ITEM_MAP_LOAD",bigQueryLoadingTemporaryDirectory="gs://rixo-jdbc-europe-west2/temp"
nohup gcloud dataflow jobs run copy_COUPON_CODES --project=project-x-ray --region europe-west2 --gcs-location gs://dataflow-templates-europe-west2/latest/Jdbc_to_BigQuery --parameters query="select * from COUPON_CODES",connectionURL="jdbc:ns://5514691.connect.api.netsuite.com:1708;ServerDataSource=NetSuite.com;encrypted=1;Ciphersuites=Ciphersuites=TLS_RSA_WITH_AES_128_CBC_SHA;CustomProperties=(AccountID=5514691;RoleID=1057)",username="mark.rittman@rittmananalytics.com",password="Rittman123",driverClassName="com.netsuite.jdbc.openaccess.OpenAccessDriver",driverJars="gs://rixo-jdbc-europe-west2/NQjc.jar",outputTable="project-x-ray:netsuite_jdbc.COUPON_CODES_LOAD",bigQueryLoadingTemporaryDirectory="gs://rixo-jdbc-europe-west2/temp"
nohup gcloud dataflow jobs run copy_INBOUND_SHIPMENTS --project=project-x-ray --region europe-west2 --gcs-location gs://dataflow-templates-europe-west2/latest/Jdbc_to_BigQuery --parameters query="select * from INBOUND_SHIPMENTS",connectionURL="jdbc:ns://5514691.connect.api.netsuite.com:1708;ServerDataSource=NetSuite.com;encrypted=1;Ciphersuites=Ciphersuites=TLS_RSA_WITH_AES_128_CBC_SHA;CustomProperties=(AccountID=5514691;RoleID=1057)",username="mark.rittman@rittmananalytics.com",password="Rittman123",driverClassName="com.netsuite.jdbc.openaccess.OpenAccessDriver",driverJars="gs://rixo-jdbc-europe-west2/NQjc.jar",outputTable="project-x-ray:netsuite_jdbc.INBOUND_SHIPMENTS_LOAD",bigQueryLoadingTemporaryDirectory="gs://rixo-jdbc-europe-west2/temp"
nohup gcloud dataflow jobs run copy_PROMOTION_CODES --project=project-x-ray --region europe-west2 --gcs-location gs://dataflow-templates-europe-west2/latest/Jdbc_to_BigQuery --parameters query="select * from PROMOTION_CODES",connectionURL="jdbc:ns://5514691.connect.api.netsuite.com:1708;ServerDataSource=NetSuite.com;encrypted=1;Ciphersuites=Ciphersuites=TLS_RSA_WITH_AES_128_CBC_SHA;CustomProperties=(AccountID=5514691;RoleID=1057)",username="mark.rittman@rittmananalytics.com",password="Rittman123",driverClassName="com.netsuite.jdbc.openaccess.OpenAccessDriver",driverJars="gs://rixo-jdbc-europe-west2/NQjc.jar",outputTable="project-x-ray:netsuite_jdbc.PROMOTION_CODES_LOAD",bigQueryLoadingTemporaryDirectory="gs://rixo-jdbc-europe-west2/temp"
nohup gcloud dataflow jobs run copy_EMPLOYEES --project=project-x-ray --region europe-west2 --gcs-location gs://dataflow-templates-europe-west2/latest/Jdbc_to_BigQuery --parameters query="select * from EMPLOYEES",connectionURL="jdbc:ns://5514691.connect.api.netsuite.com:1708;ServerDataSource=NetSuite.com;encrypted=1;Ciphersuites=Ciphersuites=TLS_RSA_WITH_AES_128_CBC_SHA;CustomProperties=(AccountID=5514691;RoleID=1057)",username="mark.rittman@rittmananalytics.com",password="Rittman123",driverClassName="com.netsuite.jdbc.openaccess.OpenAccessDriver",driverJars="gs://rixo-jdbc-europe-west2/NQjc.jar",outputTable="project-x-ray:netsuite_jdbc.EMPLOYEES_LOAD",bigQueryLoadingTemporaryDirectory="gs://rixo-jdbc-europe-west2/temp"
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.ITEM_FULFILLMENTS`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.COMPANIES`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.WMS_EXTERNAL_LABEL_DETAILS`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.WMS_SHIP_MANIFEST`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.CUSTOMER_CURRENCIES`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.ENTITY_STATUS_HISTORY`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.CUSTOMER_SUBSIDIARY_MAP`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.CUSTOMERS`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.WMS_SERIAL_ENTRY`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.CLIENT_AUDIT_TRAIL`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.WMS_COMMODITY_SHIPMENT`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.INBOUND_SHIPMENT_ITEMS`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.CYCLE_COUNT_PLAN_BINS_MAP`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.CONTACTS`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.VENDORS`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.CYCLE_COUNT_PLAN_ITEM_MAP`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.COUPON_CODES`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.INBOUND_SHIPMENTS`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.PROMOTION_CODES`'
bq query --use_legacy_sql=false 'drop table `project-x-ray.netsuite_jdbc.EMPLOYEES`'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.ITEM_FULFILLMENTS` as select * from  `project-x-ray.netsuite_jdbc.ITEM_FULFILLMENTS_LOAD`'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.COMPANIES` as select * from  `project-x-ray.netsuite_jdbc.COMPANIES_LOAD`'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.WMS_EXTERNAL_LABEL_DETAILS` as select * from  `project-x-ray.netsuite_jdbc.WMS_EXTERNAL_LABEL_DETAILS_LOAD`'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.WMS_SHIP_MANIFEST` as select * from  `project-x-ray.netsuite_jdbc.WMS_SHIP_MANIFEST_LOAD`'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.CUSTOMER_CURRENCIES` as select * from  `project-x-ray.netsuite_jdbc.CUSTOMER_CURRENCIES_LOAD`'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.ENTITY_STATUS_HISTORY` as select * from  `project-x-ray.netsuite_jdbc.ENTITY_STATUS_HISTORY_LOAD`'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.CUSTOMER_SUBSIDIARY_MAP` as select * from  `project-x-ray.netsuite_jdbc.CUSTOMER_SUBSIDIARY_MAP_LOAD`'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.CUSTOMERS` as select * from  `project-x-ray.netsuite_jdbc.CUSTOMERS_LOAD`'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.WMS_SERIAL_ENTRY` as select * from  `project-x-ray.netsuite_jdbc.WMS_SERIAL_ENTRY_LOAD`'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.CLIENT_AUDIT_TRAIL` as select * from  `project-x-ray.netsuite_jdbc.CLIENT_AUDIT_TRAIL_LOAD`'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.WMS_COMMODITY_SHIPMENT` as select * from  `project-x-ray.netsuite_jdbc.WMS_COMMODITY_SHIPMENT_LOAD`'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.INBOUND_SHIPMENT_ITEMS` as select * from  `project-x-ray.netsuite_jdbc.INBOUND_SHIPMENT_ITEMS_LOAD`'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.CYCLE_COUNT_PLAN_BINS_MAP` as select * from  `project-x-ray.netsuite_jdbc.CYCLE_COUNT_PLAN_BINS_MAP_LOAD`'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.CONTACTS` as select * from `project-x-ray.netsuite_jdbc.CONTACTS_LOAD`'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.VENDORS` as select * from `project-x-ray.netsuite_jdbc.VENDORS_LOAD`'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.CYCLE_COUNT_PLAN_ITEM_MAP` as select * from  `project-x-ray.netsuite_jdbc.CYCLE_COUNT_PLAN_ITEM_MAP_LOAD`'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.COUPON_CODES` as select * from `project-x-ray.netsuite_jdbc.COUPON_CODES_LOAD`'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.INBOUND_SHIPMENTS` as select * from  `project-x-ray.netsuite_jdbc.INBOUND_SHIPMENTS_LOAD`'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.PROMOTION_CODES` as select * from  `project-x-ray.netsuite_jdbc.PROMOTION_CODES_LOAD`'
bq query --use_legacy_sql=false 'create table  `project-x-ray.netsuite_jdbc.EMPLOYEES` as select * from  `project-x-ray.netsuite_jdbc.EMPLOYEES_LOAD`'
bq query --use_legacy_sql=false 'insert into project-x-ray.netsuite_ddl.top_50x_refresh_history select row_count, table_name, current_timestamp from project-x-ray.netsuite_ddl.top_50x_tables'
set echo off
