WITH source AS (
SELECT DISTINCT
avg_cost_per_click,
index,
competition,
search_volume,
search_locale_id,
starred,
search_type,
path,
id,
rank,
country_code,
search_engine_id,
highest_ranking_page,
name,
locale,
_sdc_table_version,
region,
keyword,
keyword_id,
_sdc_received_at,
_sdc_sequence,
rank_created_at,
CAST(SAFE.SUBSTR(rank_created_at, 0, 10)AS date) AS rank_date,
created_at,
search_volume_id,
preferred_landing_page_id,
locale_short,
_sdc_batched_at,
TIMESTAMP_MILLIS(date_period) as date_period,
row_number() over (PARTITION BY id order by date_period) AS row_number
from `client-enux`.`apiaccuranker`.`keywords`
)

SELECT 
id,
keyword_id,
avg_cost_per_click,
competition,
search_volume,
search_locale_id,
starred,
search_type,
path AS path_raw,
REGEXP_EXTRACT(CONCAT("www.fluentu.com",path),r'^([^\?]*)\??') as path,
REGEXP_REPLACE(highest_ranking_page,r'^[Hh]ttps?:\/?\/?','') as highest_ranking_page,
rank,
country_code,
search_engine_id,
highest_ranking_page AS raw_highest_ranking_page,
name,
locale,
region,
keyword,
rank_created_at,
rank_date,
created_at,
search_volume_id,
preferred_landing_page_id,
locale_short,
date_period,
max(date_period) over (PARTITION by keyword_id) AS lastest_date_period
FROM source 
WHERE row_number = 1
AND coalesce(path, highest_ranking_page) is not null
