{% if  var("marketing_warehouse_ad_campaign_sources") and var("product_warehouse_event_sources") and var("marketing_attribution_enabled")%}
{% if target.type == 'snowflake' %}

{{
    config(
      alias='ad_spend_roi_fact',
      materialized='table'
    )
}}

with ad_campaign_stats as (
  select
    *
  from
    {{ ref('wh_ad_campaign_performance_fact') }}
),
  revenue_attribution as (
    select
      date_trunc('DAY',session_start_ts) as campaign_ts,
      platform,
      campaign_id,
      ad_group_id,
      converted_ts,
      min_converted_ts,
      session_id,
      web_session_pk,
      utm_source,
      utm_content,
      utm_medium,
      utm_campaign,
      referrer_host,
      referrer_domain ,
      channel,
      is_non_direct_channel,
      is_paid_channel,
      sum(user_registration_first_click_attrib_conversions) user_registration_first_click_attrib_conversions,
      sum(user_registration_first_non_direct_click_attrib_conversions) user_registration_first_non_direct_click_attrib_conversions,
      sum(user_registration_first_paid_click_attrib_conversions) user_registration_first_paid_click_attrib_conversions,
      sum(user_registration_last_click_attrib_conversions) user_registration_last_click_attrib_conversions,
      sum(user_registration_last_non_direct_click_attrib_conversions) user_registration_last_non_direct_click_attrib_conversions,
      sum(user_registration_last_paid_click_attrib_conversions) user_registration_last_paid_click_attrib_conversions,
      sum(user_registration_even_click_attrib_conversions) user_registration_even_click_attrib_conversions,
      sum(user_registration_time_decay_attrib_conversions) user_registration_time_decay_attrib_conversions,
      sum(first_order_first_click_attrib_conversions) first_order_first_click_attrib_conversions,
      sum(first_order_first_non_direct_click_attrib_conversions) first_order_first_non_direct_click_attrib_conversions,
      sum(first_order_first_paid_click_attrib_conversions) first_order_first_paid_click_attrib_conversions,
      sum(first_order_last_click_attrib_conversions) first_order_last_click_attrib_conversions,
      sum(first_order_last_non_direct_click_attrib_conversions) first_order_last_non_direct_click_attrib_conversions,
      sum(first_order_last_paid_click_attrib_conversions) first_order_last_paid_click_attrib_conversions,
      sum(first_order_even_click_attrib_conversions) first_order_even_click_attrib_conversions,
      sum(first_order_time_decay_attrib_conversions) first_order_time_decay_attrib_conversions,
      sum(first_order_first_click_attrib_revenue) first_order_first_click_attrib_revenue,
      sum(first_order_first_non_direct_click_attrib_revenue) first_order_first_non_direct_click_attrib_revenue,
      sum(first_order_first_paid_click_attrib_revenue) first_order_first_paid_click_attrib_revenue,
      sum(first_order_last_click_attrib_revenue) first_order_last_click_attrib_revenue,
      sum(first_order_last_non_direct_click_attrib_revenue) first_order_last_non_direct_click_attrib_revenue,
      sum(first_order_last_paid_click_attrib_revenue) first_order_last_paid_click_attrib_revenue,
      sum(first_order_even_click_attrib_revenue) first_order_even_click_attrib_revenue,
      sum(first_order_time_decay_attrib_revenue) first_order_time_decay_attrib_revenue,
      sum(first_order_first_click_total_lifetime_value_30d) first_order_first_click_total_lifetime_value_30d,
      sum(first_order_first_non_direct_click_total_lifetime_value_30d) first_order_first_non_direct_click_total_lifetime_value_30d,
      sum(first_order_last_click_total_lifetime_value_30d) first_order_last_click_total_lifetime_value_30d,
      sum(first_order_last_non_direct_click_total_lifetime_value_30d) first_order_last_non_direct_click_total_lifetime_value_30d,
      sum(first_order_last_paid_click_total_lifetime_value_30d) first_order_last_paid_click_total_lifetime_value_30d,
      sum(first_order_even_click_total_lifetime_value_30d) first_order_even_click_total_lifetime_value_30d,
      sum(first_order_time_decay_total_lifetime_value_30d) first_order_time_decay_total_lifetime_value_30d,
      sum(first_order_first_click_total_lifetime_value_60d) first_order_first_click_total_lifetime_value_60d,
      sum(first_order_first_non_direct_click_total_lifetime_value_60d) first_order_first_non_direct_click_total_lifetime_value_60d,
      sum(first_order_last_click_total_lifetime_value_60d) first_order_last_click_total_lifetime_value_60d,
      sum(first_order_last_non_direct_click_total_lifetime_value_60d) first_order_last_non_direct_click_total_lifetime_value_60d,
      sum(first_order_last_paid_click_total_lifetime_value_60d) first_order_last_paid_click_total_lifetime_value_60d,
      sum(first_order_even_click_total_lifetime_value_60d) first_order_even_click_total_lifetime_value_60d,
      sum(first_order_time_decay_total_lifetime_value_60d) first_order_time_decay_total_lifetime_value_60d,
      sum(first_order_first_click_total_lifetime_value_90d) first_order_first_click_total_lifetime_value_90d,
      sum(first_order_first_non_direct_click_total_lifetime_value_90d) first_order_first_non_direct_click_total_lifetime_value_90d,
      sum(first_order_last_click_total_lifetime_value_90d) first_order_last_click_total_lifetime_value_90d,
      sum(first_order_last_non_direct_click_total_lifetime_value_90d) first_order_last_non_direct_click_total_lifetime_value_90d,
      sum(first_order_last_paid_click_total_lifetime_value_90d) first_order_last_paid_click_total_lifetime_value_90d,
      sum(first_order_even_click_total_lifetime_value_90d) first_order_even_click_total_lifetime_value_90d,
      sum(first_order_time_decay_total_lifetime_value_90d) first_order_time_decay_total_lifetime_value_90d,
      sum(first_order_first_click_total_lifetime_value_180d) first_order_first_click_total_lifetime_value_180d,
      sum(first_order_first_non_direct_click_total_lifetime_value_180d) first_order_first_non_direct_click_total_lifetime_value_180d,
      sum(first_order_last_click_total_lifetime_value_180d) first_order_last_click_total_lifetime_value_180d,
      sum(first_order_last_non_direct_click_total_lifetime_value_180d) first_order_last_non_direct_click_total_lifetime_value_180d,
      sum(first_order_last_paid_click_total_lifetime_value_180d) first_order_last_paid_click_total_lifetime_value_180d,
      sum(first_order_even_click_total_lifetime_value_180d) first_order_even_click_total_lifetime_value_180d,
      sum(first_order_time_decay_total_lifetime_value_180d) first_order_time_decay_total_lifetime_value_180d,
      sum(first_order_first_click_total_lifetime_value_365d) first_order_first_click_total_lifetime_value_365d,
      sum(first_order_first_non_direct_click_total_lifetime_value_365d) first_order_first_non_direct_click_total_lifetime_value_365d,
      sum(first_order_last_click_total_lifetime_value_365d) first_order_last_click_total_lifetime_value_365d,
      sum(first_order_last_non_direct_click_total_lifetime_value_365d) first_order_last_non_direct_click_total_lifetime_value_365d,
      sum(first_order_last_paid_click_total_lifetime_value_365d) first_order_last_paid_click_total_lifetime_value_365d,
      sum(first_order_even_click_total_lifetime_value_365d) first_order_even_click_total_lifetime_value_365d,
      sum(first_order_time_decay_total_lifetime_value_365d) first_order_time_decay_total_lifetime_value_365d,
      sum(repeat_order_first_click_attrib_conversions) repeat_order_first_click_attrib_conversions,
      sum(repeat_order_first_non_direct_click_attrib_conversions) repeat_order_first_non_direct_click_attrib_conversions,
      sum(repeat_order_first_paid_click_attrib_conversions) repeat_order_first_paid_click_attrib_conversions,
      sum(repeat_order_last_click_attrib_conversions) repeat_order_last_click_attrib_conversions,
      sum(repeat_order_last_non_direct_click_attrib_conversions) repeat_order_last_non_direct_click_attrib_conversions,
      sum(repeat_order_last_paid_click_attrib_conversions) repeat_order_last_paid_click_attrib_conversions,
      sum(repeat_order_even_click_attrib_conversions) repeat_order_even_click_attrib_conversions,
      sum(repeat_order_time_decay_attrib_conversions) repeat_order_time_decay_attrib_conversions,
      sum(repeat_order_first_click_attrib_revenue) repeat_order_first_click_attrib_revenue,
      sum(repeat_order_first_non_direct_click_attrib_revenue) repeat_order_first_non_direct_click_attrib_revenue,
      sum(repeat_order_first_paid_click_attrib_revenue) repeat_order_first_paid_click_attrib_revenue,
      sum(repeat_order_last_click_attrib_revenue) repeat_order_last_click_attrib_revenue,
      sum(repeat_order_last_non_direct_click_attrib_revenue) repeat_order_last_non_direct_click_attrib_revenue,
      sum(repeat_order_last_paid_click_attrib_revenue) repeat_order_last_paid_click_attrib_revenue,
      sum(repeat_order_even_click_attrib_revenue) repeat_order_even_click_attrib_revenue,
      sum(repeat_order_time_decay_attrib_revenue) repeat_order_time_decay_attrib_revenue
    from
      {{ ref('wh_attribution_fact') }}
    group by
      1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
  )
select
    a.campaign_ts ,
    a.platform ,
    a.account_id ,
    a.account_name ,
    a.campaign_id ,
    a.campaign_name ,
    a.ad_group_id ,
    a.ad_group_name ,
    a.reported_clicks ,
    a.reported_impressions ,
    a.reported_spend ,
    a.reported_cpc ,
    a.reported_ctr ,
    a.actual_clicks ,
    a.actual_cpc ,
    a.actual_ctr ,
    a.campaign_start_ts ,
    a.ad_group_start_ts ,
    a.days_since_campaign_start_ts ,
    a.days_since_ad_group_start_ts ,
    r.converted_ts,
    r.min_converted_ts,
    r.session_id,
    r.web_session_pk,
    r.utm_source,
    r.utm_content,
    r.utm_medium,
    r.utm_campaign,
    r.referrer_host,
    r.referrer_domain ,
    r.channel,
    r.is_non_direct_channel,
    r.is_paid_channel,
    r.user_registration_first_click_attrib_conversions,
    r.user_registration_first_non_direct_click_attrib_conversions,
    r.user_registration_first_paid_click_attrib_conversions,
    r.user_registration_last_click_attrib_conversions,
    r.user_registration_last_non_direct_click_attrib_conversions,
    r.user_registration_last_paid_click_attrib_conversions,
    r.user_registration_even_click_attrib_conversions,
    r.user_registration_time_decay_attrib_conversions,
    r.first_order_first_click_attrib_conversions,
    r.first_order_first_non_direct_click_attrib_conversions,
    r.first_order_first_paid_click_attrib_conversions,
    r.first_order_last_click_attrib_conversions,
    r.first_order_last_non_direct_click_attrib_conversions,
    r.first_order_last_paid_click_attrib_conversions,
    r.first_order_even_click_attrib_conversions,
    r.first_order_time_decay_attrib_conversions,
    r.first_order_first_click_attrib_revenue,
    r.first_order_first_non_direct_click_attrib_revenue,
    r.first_order_first_paid_click_attrib_revenue,
    r.first_order_last_click_attrib_revenue,
    r.first_order_last_non_direct_click_attrib_revenue,
    r.first_order_last_paid_click_attrib_revenue,
    r.first_order_even_click_attrib_revenue,
    r.first_order_time_decay_attrib_revenue,
    r.first_order_first_click_total_lifetime_value_30d,
    r.first_order_first_non_direct_click_total_lifetime_value_30d,
    r.first_order_last_click_total_lifetime_value_30d,
    r.first_order_last_non_direct_click_total_lifetime_value_30d,
    r.first_order_last_paid_click_total_lifetime_value_30d,
    r.first_order_even_click_total_lifetime_value_30d,
    r.first_order_time_decay_total_lifetime_value_30d,
    r.first_order_first_click_total_lifetime_value_60d,
    r.first_order_first_non_direct_click_total_lifetime_value_60d,
    r.first_order_last_click_total_lifetime_value_60d,
    r.first_order_last_non_direct_click_total_lifetime_value_60d,
    r.first_order_last_paid_click_total_lifetime_value_60d,
    r.first_order_even_click_total_lifetime_value_60d,
    r.first_order_time_decay_total_lifetime_value_60d,
    r.first_order_first_click_total_lifetime_value_90d,
    r.first_order_first_non_direct_click_total_lifetime_value_90d,
    r.first_order_last_click_total_lifetime_value_90d,
    r.first_order_last_non_direct_click_total_lifetime_value_90d,
    r.first_order_last_paid_click_total_lifetime_value_90d,
    r.first_order_even_click_total_lifetime_value_90d,
    r.first_order_time_decay_total_lifetime_value_90d,
    r.first_order_first_click_total_lifetime_value_180d,
    r.first_order_first_non_direct_click_total_lifetime_value_180d,
    r.first_order_last_click_total_lifetime_value_180d,
    r.first_order_last_non_direct_click_total_lifetime_value_180d,
    r.first_order_last_paid_click_total_lifetime_value_180d,
    r.first_order_even_click_total_lifetime_value_180d,
    r.first_order_time_decay_total_lifetime_value_180d,
    r.first_order_first_click_total_lifetime_value_365d,
    r.first_order_first_non_direct_click_total_lifetime_value_365d,
    r.first_order_last_click_total_lifetime_value_365d,
    r.first_order_last_non_direct_click_total_lifetime_value_365d,
    r.first_order_last_paid_click_total_lifetime_value_365d,
    r.first_order_even_click_total_lifetime_value_365d,
    r.first_order_time_decay_total_lifetime_value_365d,
    r.repeat_order_first_click_attrib_conversions,
    r.repeat_order_first_non_direct_click_attrib_conversions,
    r.repeat_order_first_paid_click_attrib_conversions,
    r.repeat_order_last_click_attrib_conversions,
    r.repeat_order_last_non_direct_click_attrib_conversions,
    r.repeat_order_last_paid_click_attrib_conversions,
    r.repeat_order_even_click_attrib_conversions,
    r.repeat_order_time_decay_attrib_conversions,
    r.repeat_order_first_click_attrib_revenue,
    r.repeat_order_first_non_direct_click_attrib_revenue,
    r.repeat_order_first_paid_click_attrib_revenue,
    r.repeat_order_last_click_attrib_revenue,
    r.repeat_order_last_non_direct_click_attrib_revenue,
    r.repeat_order_last_paid_click_attrib_revenue,
    r.repeat_order_even_click_attrib_revenue,
    r.repeat_order_time_decay_attrib_revenue
from
  ad_campaign_stats a
left join
  revenue_attribution r
on
  a.campaign_ts = r.campaign_ts
and
  a.campaign_id = r.campaign_id
and
  a.ad_group_id = r.ad_group_id
and
  a.platform = r.platform

  {% endif %}
  {% endif %}
